---
sidebar: sidebar 
permalink: adjust-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: NetApp Workload Factory 에서 볼륨의 볼륨 용량을 언제든지 수동으로 조정할 수 있습니다. 
---
= NetApp Workload Factory 에서 볼륨 용량 조정
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 콘솔에서 언제든지 볼륨의 볼륨 용량을 수동으로 조정할 수 있습니다.

선택적으로 다음을 수행할 수 있습니다.link:edit-volume-autogrow.html["자동 확장 기능을 활성화합니다"] Workload Factory가 볼륨 용량을 관리하도록 하세요.

.이 작업에 대해
볼륨의 프로비저닝된 크기를 늘리거나 줄여 볼륨 용량을 조정할 수 있습니다.  다음 표는 볼륨 유형별 최소 및 최대 볼륨 크기를 보여줍니다.

[cols="1,1,1"]
|===
| 볼륨 유형 | 최소 크기 | 최대 크기 


| FlexVol 볼륨 | 20미비 | 300티비 


| FlexGroup 볼륨 | 800기가바이트 | 2파이비 
|===
iSCSI LUN의 경우 볼륨 크기를 늘리면 호스트 LUN의 크기도 늘어납니다.  볼륨 용량을 늘린 후 호스트 운영 체제에서 제공하는 절차에 따라 LUN의 새로운 크기를 확인하고 LUN의 파일 시스템을 확장합니다.

볼륨 크기 감소는 NFS 및 SMB/CIFS 볼륨에만 지원됩니다.

.시작하기 전에
볼륨 용량을 조정하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."]. 링크가 연결되면 이 작업으로 돌아갑니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 저장소 타일에서 *저장소로 이동*을 선택합니다.
. 저장소 메뉴에서 *FSx for ONTAP*를 선택합니다.
. *FSx for ONTAP*에서 업데이트할 볼륨이 있는 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. 볼륨 탭에서 용량을 조정할 볼륨의 작업 메뉴를 선택합니다.
. *기본 동작*을 선택한 다음 *볼륨 용량 조정*을 선택합니다.
. 볼륨 용량 조정 대화 상자에서 *프로비저닝된 용량*과 단위를 설정합니다.
. 변경 사항을 적용하려면 *조정*을 선택하세요.


.관련 정보
* link:edit-volume-autogrow.html["Workload Factory에서 볼륨 자동 증가 활성화"]
* link:rebalance-volume.html["Workload Factory에서 볼륨 재조정"]

