---
sidebar: sidebar 
permalink: apply-block-device-tags.html 
keywords: tags, EC2 tags, ONTAP tags, block storage tags, apply tags to block devices 
summary: NetApp Workload Factory에서 리소스 관리를 위해 블록 디바이스에 ONTAP 수준 태그를 자동으로 적용합니다. 
---
= NetApp Workload Factory에서 블록 디바이스에 ONTAP 수준 태그 적용
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory의 기본 EC2 사용자 데이터 스크립트를 사용하여 AWS EC2 인스턴스 배포 중에 블록 디바이스를 자동으로 생성하고 태그를 지정할 수 있습니다. AWS EC2 콘솔에서 EC2 인스턴스를 배포할 때 인스턴스 시작 마법사 템플릿에 EC2 사용자 데이터 스크립트를 추가하세요. 배포 후 Workload Factory는 스크립트에서 수집한 메타데이터를 사용하여 블록 디바이스에 ONTAP 수준 태그를 적용합니다. 이러한 태그를 통해 각 블록 디바이스를 사용하는 호스트를 확인할 수 있으므로 문제 해결이나 감사 시 사용량과 해당 호스트를 신속하게 연결할 수 있습니다.

.이 작업에 대해
EC2 사용자 데이터 스크립트는 EC2 인스턴스 배포 중에 블록 디바이스를 생성하고 ONTAP 수준의 EC2 태그를 블록 디바이스에 적용합니다.

블록 디바이스에 적용되는 _EC2 태그_에는 EC2 이름, EC2 ID 및 EC2 인스턴스 내 블록 디바이스의 마운트 경로가 포함됩니다.

.단계
. link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-instance-wizard.html["EC2 인스턴스 시작을 위한 Amazon Elastic Compute Cloud 지침"]를 사용하여 AWS EC2 콘솔에서 인스턴스 시작 마법사를 따르십시오.
. EC2 사용자 데이터 스크립트를 인스턴스 시작 마법사 템플릿에 추가하여 블록 디바이스를 자동으로 생성하고 태그를 지정합니다.
+
GitHub 저장소 FSx-ONTAP-sample-scripts로 이동하여 link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/ec2-user-data-iscsi-create-and-mount["EC2 사용자 데이터 스크립트"]을(를) 다운로드하세요.

. 인스턴스를 시작합니다.
+
EC2 사용자 데이터 스크립트는 EC2 인스턴스에 호스팅된 새 블록 스토리지 디바이스에 ONTAP 수준 태그를 자동으로 적용합니다.

. 기존 EC2 인스턴스의 경우 사용자 데이터 스크립트는 재부팅 후에만 적용됩니다.


.결과
EC2 태그는 연결된 FSx for ONTAP 파일 시스템 내의 블록 디바이스 테이블에 나타납니다.

.관련 정보
* link:create-igroup.html["NetApp Workload Factory에서 파일 시스템용 이니시에이터 그룹(igroup)을 생성합니다"]
* link:manage-block-storage.html["NetApp Workload Factory에서 파일 시스템의 블록 스토리지를 관리합니다"]

