---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: 데이터 보호 볼륨을 복제하거나 볼륨 데이터의 복제를 단계적으로 수행하여 데이터 보호를 3차 시스템으로 확장하거나 데이터를 마이그레이션합니다. 
---
= BlueXP  워크로드 공장에서 데이터 보호 볼륨 복제
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터 보호 볼륨을 복제하거나 볼륨 데이터의 복제를 단계적으로 수행하여 데이터 보호를 3차 시스템으로 확장하거나 데이터를 마이그레이션합니다.

.이 작업에 대해
BlueXP  워크로드 공장에서 데이터 보호 볼륨 복제를 지원합니다. ONTAP에서 데이터 보호 볼륨 복제는 _ mirror-mirror cascascade deployd _ 로 간주됩니다. 미러 계단식 배열 구축은 소스 볼륨이 2차 볼륨으로 미러링되고 2차 볼륨이 3차 볼륨으로 미러링되는 관계 체인으로 구성됩니다. 2차 볼륨을 사용할 수 없게 되면 새로운 기준 전송을 수행하지 않고도 1차 볼륨과 3차 볼륨 간의 관계를 동기화할 수 있습니다.

이 기능은 ONTAP 버전 9.6 이상이 설치된 FSx for ONTAP 파일 시스템에서 지원됩니다. 을 link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["호환되는 ONTAP 버전에 대한 ONTAP 설명서"^]참조하십시오.


NOTE: 관계의 소스 볼륨이 데이터 보호 볼륨이고 다른 관계의 타겟인 경우에는 복제 관계를 되돌릴 수 없습니다.

.시작하기 전에
다중 구간 구성의 일부인 볼륨은 다시 동기화하는 데 시간이 오래 걸릴 수 있습니다.

[role="tabbed-block"]
====
.단일 볼륨을 복제합니다
--
데이터 보호(DP) 볼륨을 복제할 수 있습니다.


NOTE: 데이터 보호 볼륨의 복제본 하나가 지원됩니다. DP 볼륨의 두 번째 복제본을 생성할 수 없습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 Go to storage inventory 를 선택합니다.
. FSx for ONTAP 탭에서 업데이트할 파일 시스템의 세 점 메뉴를 선택한 다음 관리 를 선택합니다.
. Volumes 탭을 선택합니다.
. 데이터 보호 볼륨(DP/복제된 볼륨)의 3점 메뉴를 선택하고 * Replicate volume data * 를 선택합니다.
. 복제 생성 페이지의 복제 타겟에서 다음을 제공합니다.
+
.. * FSx for ONTAP 파일 시스템 *: 대상 FSx for ONTAP 파일 시스템에 대한 자격 증명, 지역 및 FSx for ONTAP 파일 시스템 이름을 선택합니다.
.. * 스토리지 VM 이름 *: 드롭다운 메뉴에서 스토리지 VM을 선택합니다.
.. * 볼륨 이름 * : 대상 볼륨 이름은 다음 형식으로 자동으로 `{OriginalVolumeName}_copy`생성됩니다. 자동 생성된 볼륨 이름을 사용하거나 다른 볼륨 이름을 입력할 수 있습니다.
.. * 활용 사례 *: 다음 복제 사용 사례 중 하나를 선택하십시오.
+
*** 마이그레이션: 데이터를 대상 FSx for ONTAP 파일 시스템으로 전송합니다
*** 핫 재해 복구: 중요한 워크로드에 대한 고가용성 및 신속한 재해 복구를 보장합니다
*** 콜드 또는 아카이브 재해 복구:
+
**** 콜드 재해 복구: 더 긴 RTO(복구 시간 목표) 및 RPO(복구 시점 개체)를 사용하여 비용을 절감합니다
**** 아카이브: 장기 스토리지 및 규정 준수를 위해 데이터 복제


*** 기타


.. * Tiering policy *: 타겟 볼륨에 저장된 데이터에 대한 계층화 정책을 선택합니다. 선택한 활용 사례에 따라 계층화 정책은 기본적으로 활용 사례에 대해 권장되는 계층화 정책으로 설정됩니다.
+
_Balanced (Auto) _ 는 워크로드 팩토리 FSx for ONTAP 사용자 인터페이스를 사용하여 볼륨을 생성할 때의 기본 계층화 정책입니다. 볼륨 계층화 정책에 대한 자세한 내용은 AWS FSx for NetApp ONTAP 설명서 를 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["볼륨 스토리지 용량"^] 참조하십시오.

.. * 최대 전송 속도 *: * 제한 * 을 선택하고 최대 전송 제한(MB/s)을 입력합니다 또는 * 무제한 * 을 선택합니다.
+
제한이 없으면 네트워크 및 애플리케이션 성능이 저하될 수 있습니다. 또는 중요한 워크로드(예: 재해 복구에 주로 사용되는 워크로드)에 FSx for ONTAP 파일 시스템에 대해 무제한 전송 속도를 사용하는 것이 좋습니다.



. Replication settings(복제 설정) 에서 다음을 제공합니다.
+
.. * 복제 간격 *: 소스 볼륨에서 타겟 볼륨으로 스냅샷이 전송되는 빈도를 선택합니다.
.. *장기 보존*: 장기 보존을 위해 스냅샷을 선택적으로 사용할 수 있습니다.
+
장기 보존을 사용하도록 설정한 경우 기존 정책을 선택하거나 새 정책을 생성하여 복제할 스냅샷 및 유지할 스냅샷 수를 정의합니다.

+
*** 기존 정책 선택 * 의 경우 드롭다운 메뉴에서 기존 정책을 선택합니다.
*** 새 정책 만들기 * 에 다음을 제공합니다.
+
**** * 정책 이름 *: 정책 이름을 입력하십시오.
**** * Snapshot policies *: 표에서 스냅샷 정책 빈도와 유지할 복제본 수를 선택합니다. 두 개 이상의 스냅샷 정책을 선택할 수 있습니다.






. Create * 를 선택합니다.


--
.파일 시스템의 모든 볼륨을 복제합니다
--
파일 시스템의 모든 데이터 보호(DP) 볼륨을 복제할 수 있습니다.


NOTE: 데이터 보호 볼륨의 복제본 하나가 지원됩니다. DP 볼륨의 두 번째 복제본을 생성할 수 없습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP 탭에서 볼륨이 있는 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * 복제 생성 * 을 선택합니다.
. 복제 생성 페이지의 복제 타겟에서 다음을 제공합니다.
+
.. * FSx for ONTAP 파일 시스템 *: 대상 FSx for ONTAP 파일 시스템에 대한 자격 증명, 지역 및 FSx for ONTAP 파일 시스템 이름을 선택합니다.
.. * 스토리지 VM 이름 *: 드롭다운 메뉴에서 스토리지 VM을 선택합니다.
.. * 볼륨 이름 * : 대상 볼륨 이름은 다음 형식으로 자동으로 `{OriginalVolumeName}_copy`생성됩니다.
.. * Tiering policy *: 타겟 볼륨에 저장된 데이터에 대한 계층화 정책을 선택합니다.
+
_AUTO_는 워크로드 팩토리 FSx for ONTAP 사용자 인터페이스를 사용하여 볼륨을 생성할 때의 기본 계층화 정책입니다. 볼륨 계층화 정책에 대한 자세한 내용은 AWS FSx for NetApp ONTAP 설명서 를 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["볼륨 스토리지 용량"^]참조하십시오.

.. * 최대 전송 속도 *: * 제한 * 을 선택하고 MiB/s 단위의 최대 전송 한도를 입력하십시오 또는 * 무제한 * 을 선택합니다.
+
제한이 없으면 네트워크 및 애플리케이션 성능이 저하될 수 있습니다. 또는 중요한 워크로드(예: 재해 복구에 주로 사용되는 워크로드)에 FSx for ONTAP 파일 시스템에 대해 무제한 전송 속도를 사용하는 것이 좋습니다.



. Replication settings(복제 설정) 에서 다음을 제공합니다.
+
.. * 복제 간격 *: 소스 볼륨에서 타겟 볼륨으로 스냅샷이 전송되는 빈도를 선택합니다.
.. *장기 보존*: 장기 보존을 위해 스냅샷을 선택적으로 사용할 수 있습니다.
+
장기 보존을 사용하도록 설정한 경우 기존 정책을 선택하거나 새 정책을 생성하여 복제할 스냅샷 및 유지할 스냅샷 수를 정의합니다.

+
*** 기존 정책 선택 * 의 경우 드롭다운 메뉴에서 기존 정책을 선택합니다.
*** 새 정책 만들기 * 에 다음을 제공합니다.
+
**** * 정책 이름 *: 정책 이름을 입력하십시오.
**** * Snapshot policies *: 표에서 스냅샷 정책 빈도와 유지할 복제본 수를 선택합니다. 두 개 이상의 스냅샷 정책을 선택할 수 있습니다.






. Create * 를 선택합니다.


--
====
.결과
복제된 볼륨이 복제되고 타겟 FSx for ONTAP 파일 시스템의 * 복제 관계 * 탭에 표시됩니다.
