---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords: tiering policy, change tier, change tiers, tier policy update 
summary: BlueXP  워크로드 팩토리의 계층화 정책을 변경하여 고성능 운영 스토리지 계층에서 보조 용량 풀 스토리지 계층으로 데이터를 재할당합니다. 
---
= BlueXP  워크로드 공장 에서 볼륨의 계층화 정책을 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리에서 데이터를 고성능 운영 스토리지 계층에서 보조 용량 풀 스토리지 계층으로 자동으로 재할당하도록 계층화 정책을 변경할 수 있습니다.

.이 작업에 대해
언제든지 볼륨의 계층화 정책을 변경할 수 있다. 계층화 정책은 볼륨별로 정의됩니다.

데이터를 저장할 위치를 결정하면 비용을 절감할 수 있습니다.

FSx for ONTAP에는 볼륨 데이터를 저장하기 위한 두 가지 계층이 있습니다.

* * ssd 스토리지 계층 *: 이 기본 스토리지 계층은 사용자가 가장 자주 액세스하는 데이터를 위한 것으로, _hot_data라고도 합니다. 운영 스토리지 계층에 데이터를 저장하는 것은 보조 스토리지 계층보다 비용이 더 많이 듭니다.
* * 용량 풀 스토리지 계층 *: 이 보조 스토리지 계층은 아카이빙된 데이터 또는 자주 액세스하지 않는 데이터(_COLD_DATA라고도 함)를 위한 것입니다.


link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["스토리지 용량 관리"^]스토리지 계층에 대한 자세한 내용은 AWS for FSx for NetApp ONTAP 설명서를 참조하십시오.

.시작하기 전에
계층화 정책을 변경하기 전에 사용 가능한 계층화 정책을 검토하십시오.

* * Balanced (Auto) *: 사용자 인터페이스를 사용하여 볼륨을 생성할 때 기본 계층화 정책. 자주 액세스하는 데이터를 SSD 스토리지 계층에 유지하고, 자주 액세스하지 않는 데이터와 스냅샷을 냉각 기간이 끝난 후 용량 풀 스토리지 계층에 계층화합니다. 일반적인 운영 워크로드에 권장됩니다.
* * 비용 최적화(모두) *: 모든 스냅샷과 데이터를 용량 풀 스토리지 계층으로 계층화합니다. 2차 타겟에 권장됩니다.
* * 성능 최적화(스냅샷만 해당) *: 스냅샷 데이터만 용량 풀 스토리지 계층에 계층화합니다. 미션 크리티컬 데이터베이스와 같이 지연 시간이 짧은 워크로드에 권장됩니다.
* * 없음 *: 볼륨 데이터를 SSD 스토리지 계층에 보관하므로 용량 풀 스토리지 계층으로 이동할 수 없습니다.


일부 계층화 정책에는 볼륨의 사용자 데이터가 "콜드"로 간주되고 용량 풀 스토리지 계층으로 이동되려면 볼륨의 사용자 데이터가 비활성 상태로 유지되어야 하는 시간을 설정하는 관련 최소 냉각 기간 또는 _cooling days_ 이 있습니다. 냉각 기간은 데이터가 디스크에 기록될 때 시작됩니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 업데이트할 볼륨이 있는 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. Volumes 탭에서 계층화 정책을 변경할 볼륨의 3개 점이 있는 메뉴를 선택합니다.
. 고급 조치 * 를 선택한 다음 * 계층화 정책 변경 * 을 선택합니다.
. 계층화 정책 변경 페이지에서 소스 볼륨의 계층화 정책을 복제하도록 선택하거나 다음 계층화 정책 중 하나를 선택합니다.
+
** * 균형(자동) *: 냉각 일수를 입력합니다.
** * 비용 최적화(모두) *
** * 성능 최적화(스냅샷만 해당) *: 냉각 일수를 입력합니다.
** * 없음 *


. Apply * 를 선택합니다.

