---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords:  
summary: 데이터를 고성능 운영 스토리지 계층에서 보조 용량 풀 스토리지 계층으로 다시 할당하도록 계층화 정책을 변경합니다. 
---
= 볼륨의 계층화 정책을 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
고성능 운영 스토리지 계층에서 보조 용량 풀 스토리지 계층으로 데이터를 자동으로 재할당하도록 계층화 정책을 변경합니다.

.이 작업에 대해
언제든지 볼륨의 계층화 정책을 변경할 수 있다. 계층화 정책은 볼륨별로 정의됩니다.

데이터를 저장할 위치를 결정하면 비용을 절감할 수 있습니다.

FSx for ONTAP에는 볼륨 데이터를 저장하기 위한 두 가지 계층이 있습니다.

* * ssd 스토리지 계층 *: 이 기본 스토리지 계층은 사용자가 가장 자주 액세스하는 데이터를 위한 것으로, _hot_data라고도 합니다. 운영 스토리지 계층에 데이터를 저장하는 것은 보조 스토리지 계층보다 비용이 더 많이 듭니다.
* * 용량 풀 스토리지 계층 *: 이 보조 스토리지 계층은 아카이빙된 데이터 또는 자주 액세스하지 않는 데이터(_COLD_DATA라고도 함)를 위한 것입니다.


link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["스토리지 용량 관리"^]스토리지 계층에 대한 자세한 내용은 AWS for FSx for NetApp ONTAP 설명서를 참조하십시오.

.시작하기 전에
계층화 정책을 변경하기 전에 사용 가능한 계층화 정책 4개를 검토하십시오.

* * 자동 *: 사용자 데이터와 스냅샷이 포함된 모든 콜드 데이터를 특정 기간 동안 용량 풀 스토리지 계층으로 계층화합니다.
* * 스냅샷 전용 *: 스냅샷 데이터만 용량 풀 스토리지 계층에 계층화합니다.
* * 없음 *: 모든 볼륨의 데이터를 기본 스토리지 계층에 보관합니다.
* * ALL *: 모든 사용자 데이터와 스냅샷 데이터를 콜드 데이터로 표시하고 용량 풀 스토리지 계층에 저장합니다.


일부 계층화 정책에는 볼륨의 사용자 데이터가 "콜드"로 간주되고 용량 풀 스토리지 계층으로 이동되려면 볼륨의 사용자 데이터가 비활성 상태로 유지되어야 하는 시간을 설정하는 관련 최소 냉각 기간 또는 _cooling days_ 이 있습니다. 냉각 기간은 데이터가 디스크에 기록될 때 시작됩니다.

.단계
. Workload Factory 콘솔에 로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 업데이트할 볼륨이 있는 파일 시스템의 점 3개 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. 볼륨 탭에서 계층화 정책을 변경할 볼륨의 점 3개 메뉴를 클릭합니다.
. 고급 조치 * 를 선택한 다음 * 계층화 정책 변경 * 을 선택합니다.
. 계층화 정책 변경 페이지에서 다음 계층화 정책 중 하나를 선택합니다.
+
** * 자동 *: 냉각 일수를 입력합니다.
** * 스냅샷 전용 *: 냉각 일수를 입력합니다.
** * 없음 *
** * 모두 *


. 적용 * 을 클릭합니다.

