---
sidebar: sidebar 
permalink: clone-volume.html 
keywords: clone volume, clone, clone data 
summary: BlueXP  워크로드 팩토리에서 볼륨을 클론 복제하여 테스트를 위해 원래 볼륨의 읽기-쓰기 볼륨을 만듭니다. 
---
= BlueXP  워크로드 팩토리에서 볼륨 클론 복제
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리에서 볼륨을 클론 복제하여 테스트를 위해 원래 볼륨의 읽기-쓰기 볼륨을 만듭니다.

클론은 데이터의 현재 시점 상태를 반영합니다. 또한 클론을 사용하면 운영 데이터에 대한 액세스 권한을 부여하지 않고 추가 사용자에게 데이터에 대한 액세스 권한을 부여할 수 있습니다.

.이 작업에 대해
볼륨 클로닝은 FlexClone 볼륨에만 지원됩니다.

볼륨의 클론이 생성되면 상위 볼륨의 스냅샷을 참조하여 쓰기 가능한 볼륨이 생성됩니다. 클론은 몇 초 내에 생성됩니다. 클론 복제된 데이터는 볼륨 클론에 상주하지 않고 상위 볼륨에 상주합니다. 클론 생성 후 볼륨에 기록되는 모든 새 데이터는 클론에 상주합니다.

복제된 볼륨에 상위 볼륨의 모든 데이터와 생성 후 클론에 추가된 새 데이터가 포함되도록 하려면 상위 볼륨에서 이 작업을 수행해야 link:split-cloned-volume.html["클론을 분할합니다"] 합니다. 또한 상위 볼륨에 클론이 있는 경우 해당 볼륨을 삭제할 수 없습니다. 상위 볼륨을 삭제하려면 먼저 클론을 분할해야 합니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 복제할 볼륨이 포함된 FSx for ONTAP 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템의 개요 탭에서 * Volumes * 탭을 선택합니다.
. Volumes 탭에서 클론 복제할 볼륨의 점 3개 메뉴를 선택합니다.
. Data protection actions * 를 선택한 다음 * Clone volume * 을 선택합니다.
. 클론 볼륨 대화 상자에서 볼륨 클론의 이름을 입력합니다.
. 클론 * 을 선택합니다.

