---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 구성을 정기적으로 분석하여 구성 문제가 있는지 확인합니다. 
---
= FSx for ONTAP 파일 시스템에 대한 구성 분석
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 구성을 정기적으로 분석하여 구성 문제가 있는지 확인합니다. 문제가 발견되면 Workload Factory는 문제의 내용과 파일 시스템 스토리지가 최상의 성능, 비용 효율성 및 모범 사례 준수를 달성하도록 변경해야 하는 사항을 설명합니다.

주요 기능은 다음과 같습니다.

* 일일 구성 분석
* 모범 사례 자동 검증
* 사전 예방적인 관찰 가능성
* 통찰력을 행동으로
* AWS의 잘 설계된 프레임워크 조언자




== 작동 방식

Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 배포 환경에서 실행되는 워크로드를 매일 분석합니다. 이 분석을 통해 아키텍처 상태, 인사이트 및 권장 사항을 확인할 수 있습니다.

일일 분석이 완료되면 배포의 Well-architected 대시보드에 구성 상태가 "최적화됨" 또는 "최적화되지 않음"으로 표시됩니다. 총 최적화 점수, 범주별 구성 문제, 구성 문제 및 권장 사항 목록을 확인할 수 있습니다. 구성 문제에 대한 권장 사항을 검토할 수 있습니다. 일부 문제는 Workload Factory에서 자동으로 수정되지만, 다른 문제는 수동 개입이 필요합니다. 이 경우 Workload Factory는 권장 변경 사항을 구현하는 데 도움이 되는 자세한 지침을 제공합니다.

사용 환경에 적용되지 않는 구성에 대한 분석은 제외할 수 있습니다. 이렇게 하면 불필요한 경고와 부정확한 최적화 결과를 방지할 수 있습니다. 특정 구성 분석을 제외하면 Workload Factory는 해당 구성을 전체 최적화 점수 계산에 포함하지 않습니다.



== 중요한 이유

Workload Factory는 지속적인 평가와 권장 사항 인사이트 및 문제 해결을 결합하여 대규모 스토리지, 데이터베이스 및 VMware 환경에 모범 사례를 적용합니다. Workload Factory 콘솔에서 적용되는 자동화된 수정 사항은 인적 오류를 줄이고 일관된 관리를 보장하며 워크로드 인프라 전반의 성능과 안정성을 유지합니다.



== 분석 요구 사항

파일 시스템을 완벽하게 분석하려면 다음을 수행해야 합니다.

* 링크를 연결합니다.  링크 연결을 통해 Workload Factory는 데이터 보호 및 성능과 같은 모든 파일 시스템 구성을 분석할 수 있습니다.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."]..

* AWS 계정에서 _보기, 계획 및 분석_ 권한을 부여합니다.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정에 사용 권한을 부여하는 방법에 대해 알아봅니다"^]





== 스토리지 워크로드에 대한 모범 사례 및 권장 사항

Workload Factory는 스토리지 구성을 평가하여 ONTAP 구성 모범 사례에 대한 심층적인 분석과 AWS Well-Architected Framework 준수 여부를 제공합니다. 또한, 개선 사항 및 수정 사항에 대한 권장 사항도 제시합니다.

잘 설계된 분석은 프레임워크의 다음 핵심 요소인 _안정성_, _보안_, _운영 우수성_, _비용 최적화_ 및 _성능 효율성_으로 구성을 분류합니다.



=== 안정성

안정성은 중단이 발생하더라도 워크로드가 의도된 기능을 정확하고 일관되게 수행하도록 보장합니다.

* *볼륨 백업 예약*
+
볼륨 백업은 데이터 보존 및 규정 준수 요구 사항을 충족하는 데 도움이 됩니다. 볼륨 백업을 사용하여 데이터에 대한 자동 백업 및 보존을 설정하십시오.

* *로컬 스냅샷 예약*
+
효율적인 백업과 빠른 복원을 위해 로컬 스냅샷을 예약하세요. 스냅샷은 볼륨의 특정 시점 이미지를 즉시 생성합니다.

* *지역 간 복제*
+
리전 간 복제는 데이터를 다른 AWS 리전으로 복제하여 데이터의 내구성과 가용성을 향상시킵니다. NetApp Workload Factory는 재해 복구 및 규정 준수를 위해 리전 간 복제 설정을 권장합니다.

* *데이터 복제 설정*
+
데이터 안정성을 향상시키기 위해 데이터를 동일 지역 또는 다른 지역의 FSx for ONTAP 파일 시스템으로 복제할 수 있습니다. 마이그레이션, 재해 복구 및 파일 시스템 간 장기 데이터 보존을 지원하도록 데이터 복제를 설정하십시오.

* *SSD 용량 임계값 증가*
+
SSD 스토리지 계층 용량은 지속적으로 80% 사용률을 초과해서는 안 됩니다. 이는 용량 풀 스토리지 계층에 대한 데이터 읽기 및 쓰기에 영향을 미치고 파일 시스템의 처리량 용량에 영향을 줄 수 있습니다. 용량이 부족하면 데이터 볼륨이 읽기 전용이 되고 새 데이터를 쓰려는 서비스가 실패할 수 있습니다.

* *데이터 신뢰성을 확보하기 위해 라벨을 일치시키세요*
+
데이터 안정성을 보장하려면 소스 볼륨의 스냅샷 정책 레이블과 복제 정책 레이블이 일치해야 합니다.

* *파일 용량 임계값 증가*
+
볼륨 용량 제한에 도달하지 않도록 파일 용량 임계값을 높여야 합니다. 파일 용량(inode)이 부족하면 볼륨에 추가 데이터를 기록할 수 없습니다. Workload Factory는 사용 가능한 파일 용량의 80% 미만을 지속적으로 유지하는 것을 권장합니다. 볼륨에 새 파일을 생성하려면 사용 가능한 파일 용량이 필요합니다.





=== 보안

보안은 위험 평가 및 완화 전략을 통해 데이터, 시스템 및 자산을 보호하는 데 중점을 둡니다.

* *ARP/AI 활성화*
+
NetApp AI 기반 자율형 랜섬웨어 보호(ARP/AI)는 랜섬웨어 위협으로부터 볼륨을 보호하는 데 도움을 줍니다. Workload Factory는 모든 볼륨에 대해 ARP/AI를 활성화할 것을 권장합니다.

* *볼륨에 대한 무단 액세스*
+
iSCSI를 사용하여 애플리케이션 데이터를 제공하는 볼륨은 NAS에 대한 병렬 액세스를 허용해서는 안 됩니다. Workload Factory는 iSCSI 프로토콜을 통해 액세스하는 볼륨에 대해 다른 프로토콜 사용을 제한할 것을 권장합니다.





=== 운영 우수성

운영 우수성은 최적의 아키텍처와 비즈니스 가치 제공에 중점을 둡니다.

* *자동 용량 관리 활성화*
+
SSD 계층이 임계값을 초과하지 않도록 정기적으로 관리하려면 자동 용량 관리를 활성화해야 합니다.

* *볼륨 용량 활용률 임계값*
+
Workload Factory는 볼륨 용량 사용률이 지속적으로 80%를 초과하지 않도록 권장합니다. 이를 초과할 경우 애플리케이션의 데이터 읽기 및 쓰기에 영향을 미칠 수 있습니다. 볼륨 용량 증가는 수동 또는 볼륨 자동 확장 기능을 사용하여 자동으로 수행할 수 있습니다.

* *볼륨 사용률이 거의 최대치에 도달했습니다*
+
볼륨이 거의 꽉 찼을 때 Workload Factory는 잠재적인 애플리케이션 중단을 방지하기 위해 볼륨 용량을 늘리는 조치를 취할 것을 권장합니다.

* *캐시 관계 쓰기 모드*
+
최적의 성능을 위해 Workload Factory는 워크로드에 가장 적합한 캐시 관계 쓰기 모드를 권장합니다. 쓰기 우회 모드는 작은 파일을 사용하는 읽기 중심 워크로드에서 더 나은 성능을 제공하며, 쓰기 백 모드는 큰 파일을 사용하는 쓰기 중심 워크로드에서 더 나은 성능을 제공합니다.

* *캐시 볼륨 크기 최적화*
+
Workload Factory는 최적의 크기를 유지하고 캐시가 자주 사용되는 데이터에 집중하여 효율성을 극대화할 수 있도록 캐시 볼륨에서 볼륨 자동 크기 조정 및 스크러빙을 활성화하는 것을 권장합니다.

* *스토리지 VM 논리적 보고*
+
Workload Factory에서는 볼륨 수준에서 스토리지 사용량을 더 잘 파악할 수 있도록 스토리지 VM의 기본 보고 설정을 논리적으로 설정하는 것을 권장합니다.





=== 비용 최적화

비용 최적화는 비용을 낮게 유지하면서 비즈니스에 가장 큰 가치를 얻을 수 있도록 도와줍니다.

* *콜드 데이터를 계층화하여 TCO 최적화*
+
SSD 스토리지 티어 사용률을 줄이려면 콜드 데이터 티어링을 활성화해야 합니다. 모든 볼륨에 티어링 정책을 적용하는 것이 좋습니다. FSx for ONTAP은 데이터를 지속적으로 스캔하여 콜드 데이터를 감지하고 중단 없이 용량 스토리지 풀 티어로 이동합니다.

* *스토리지 효율성 활성화*
+
스토리지 활용도를 최적화하고 SSD 계층 비용을 절감하기 위해 컴팩션, 압축, 데이터 중복 제거와 같은 스토리지 효율성 향상 기능을 활성화해야 합니다.

* *불필요한 스냅샷 및 백업 삭제*
+
비용 절감을 위해 더 이상 필요하지 않은 스냅샷과 백업은 삭제해야 합니다.

* *비활성 블록 디바이스*
+
블록 디바이스를 7일 동안 사용하지 않으면 Workload Factory에서는 비용 절감을 위해 블록 디바이스 데이터를 아카이빙하거나 사용하지 않는 블록 디바이스를 삭제할 것을 권장합니다.

* *활용도가 낮은 SSD 용량*
+
SSD 용량 계층이 제대로 활용되지 않으면 불필요한 비용이 발생할 수 있습니다. NetApp Workload Factory는 현재 사용 용량보다 20%의 여유 공간을 확보하면서 SSD 계층 용량을 줄이는 것을 권장합니다. 용량 감소 작업은 몇 시간에서 며칠까지 소요될 수 있으며, 이 시간 동안 다른 파일 시스템 작업은 지원되지 않습니다.



.다음 단계
link:improve-configurations.html["잘 설계된 파일 시스템 구성 구현"]
