---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 구성을 정기적으로 분석하여 문제가 있는지 확인합니다. 
---
= FSx for ONTAP 파일 시스템에 대한 구성 분석
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 구성을 정기적으로 분석하여 문제가 있는지 확인합니다.  문제가 발견되면 Workload Factory는 문제가 무엇인지 보여주고 파일 시스템 스토리지가 최고의 성능, 비용 효율성, 모범 사례 준수를 달성하기 위해 무엇을 변경해야 하는지 설명합니다.

주요 기능은 다음과 같습니다.

* 일일 구성 분석
* 모범 사례 자동 검증
* 사전 예방적인 관찰 가능성
* 통찰력을 행동으로
* AWS의 잘 설계된 프레임워크 조언자




== 잘 구성된 상태

파일 시스템 수준의 Workload Factory 콘솔에서 모든 FSx for ONTAP 파일 시스템에 대한 잘 설계된 상태가 나열됩니다.  잘 설계된 상태는 "문제", "분석되지 않음", "잘 설계된"으로 분류됩니다.  잘 설계된 상태를 선택하면 파일 시스템 내의 잘 설계된 상태 탭으로 이동하게 되며, 여기서 잘 설계된 점수, 구성 범주, 파일 시스템의 모든 구성을 찾을 수 있습니다.

잘 짜여진 점수:: 점수에는 현재 분석된 모든 구성이 포함되며 백분율로 표시됩니다. 25% 점수는 파일 시스템 구성의 25%가 잘 설계되었음을 의미합니다.
구성 범주:: 파일 시스템 구성은 잘 설계된 AWS 프레임워크의 다음 5가지 핵심 요소에 맞춰 여러 범주로 분류됩니다.
+
--
* _안정성_: 작업 부하가 중단되더라도 의도한 기능을 정확하고 일관되게 수행하도록 보장합니다. 구성의 예는 FSx for ONTAP 백업입니다.
* _보안_: 위험 평가 및 완화 전략을 통해 데이터, 시스템 및 자산을 보호합니다.
* _운영의 탁월성_: 최적의 아키텍처와 비즈니스 가치를 제공하는 데 중점을 둡니다.
* _비용 최적화_: 비용을 최소화하면서 비즈니스 가치를 제공하는 것을 목표로 합니다.
* _성능 효율성_: 리소스를 효율적으로 사용하여 시스템 요구 사항을 충족하고 요구 사항이 변경될 때 최적의 성능을 유지하는 데 초점을 맞춥니다.


--




== 분석 요구 사항

파일 시스템을 완벽하게 분석하려면 링크를 연결해야 합니다.  링크 연결을 통해 Workload Factory는 데이터 보호 및 성능과 같은 모든 파일 시스템 구성을 분석할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."]..

.다음 단계
link:improve-configurations.html["잘 설계된 파일 시스템 구성 구현"]
