---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: BlueXP  워크로드 공장에서 스토리지 VM에 대한 맞춤형 스냅샷 정책을 생성합니다. 
---
= BlueXP  워크로드 팩토리에서 스토리지 VM에 대한 스냅샷 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 공장에서 스토리지 VM에 대한 맞춤형 스냅샷 정책을 생성합니다. 스냅샷 정책은 시스템이 스토리지 VM에 대한 스냅샷을 생성하는 방법을 정의합니다. FSx for ONTAP 파일 시스템에서 스토리지 VM에 대한 스냅샷 정책을 생성할 수 있습니다. 여러 스토리지 VM 간에 정책을 공유할 수도 있습니다.

.이 작업에 대해
FSx for ONTAP에 대한 내장된 세 가지 스냅샷 정책과 다른 사용자 지정 스냅샷 정책을 생성할 수 있습니다.

* `default`
* `default-1weekly`
* `none`


기본적으로 모든 볼륨은 파일 시스템의 `default` 스냅샷 정책에 연결됩니다. 대부분의 워크로드에 이 정책을 사용하는 것이 좋습니다.

정책을 사용자 정의하면 스냅샷을 생성할 시기, 보존할 복제본 수 및 이름 지정 방법을 지정할 수 있습니다.

.시작하기 전에
* 스냅샷 정책을 생성한 후에는 스토리지 VM과의 연결을 수정할 수 없지만 언제든지 볼륨에서 정책을 추가하거나 제거할 수 있습니다.
* 스냅샷을 사용하기 전에 스냅샷 용량에 대해 다음 사항을 고려하십시오.
+
** 대부분의 데이터 세트의 경우 20%의 추가 용량으로 스냅샷을 최대 4주 동안 보관할 수 있습니다. 데이터가 오래되면 복원에 사용할 가능성이 줄어듭니다.
** 스냅샷의 모든 데이터를 덮어쓰면 볼륨 용량이 상당히 많이 소모되며, 이는 볼륨 용량 할당에 영향을 미칩니다.


* 사용자 지정 스냅샷 정책을 생성하려면 다음을 수행해야 link:manage-links.html["링크를 연결합니다"]합니다. 기존 링크가 없는 경우 link:create-link.html["링크를 만듭니다"] 파일 시스템의 링크를 연결하려면 * 계정 이름 * 아래에서 * 링크 * 를 선택합니다. 링크가 연결되면 이 작업으로 돌아갑니다.


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage * 에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 볼륨이 있는 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Storage VMS * 탭을 선택합니다.
. Storage VM * 탭에서 예약된 스냅샷으로 보호할 볼륨의 세 점 메뉴를 선택한 다음 * Advanced Actions *, * Manage snapshot policies * 를 차례로 선택합니다.
. 스냅샷 정책 관리 페이지에서 * 스냅샷 정책 생성 * 을 선택합니다.
. 스냅샷 정책 이름 * 필드에 스냅샷 정책의 이름을 입력합니다.
. 필요한 경우 스냅샷 정책에 대한 설명을 입력합니다.
. Policy schedule and copies * 아래에서 스냅샷을 생성할 시기를 선택합니다. 예를 들어, 매 분 또는 매시간.
+
둘 이상의 주파수를 선택할 수 있습니다.

. 사본 수 * 에 보관할 매수를 입력합니다.
+
최대 인쇄 매수는 1,023매입니다.

. 선택 사항: * 명명 규칙 * 에서 정책에 * 접두사 * 를 입력합니다.
. * 보존 레이블 * 이 자동으로 채워집니다.
+
이 레이블은 소스에서 타겟 파일 시스템으로의 복제에 지정된 스냅샷만 선택하는 데 사용되는 SnapMirror 또는 복제 레이블을 나타냅니다.

. 선택 사항: 필요한 모든 스케줄에 대해 * 변경 불가능한 스냅샷 * 을 활성화하고, 각 스케줄에 대해 * 보존 기간 * 을 설정하고, 계속하려면 문을 수락합니다.
+
변경 불가능한 스냅샷을 활성화하면 이 스냅샷 정책의 모든 스냅샷이 잠기므로 보존 기간 동안 스냅샷이 삭제되지 않습니다.

. * 스토리지 VM 간에 공유 *: 기본적으로 활성화됩니다. 설정된 경우 스냅샷 정책은 파일 시스템의 모든 스토리지 VM에서 공유됩니다. 단일 스토리지 VM에 대한 스냅샷 정책을 생성하려면 비활성화하십시오.
. Create * 를 선택합니다.


.결과
스냅샷 정책이 생성됩니다.
