---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: FSx for ONTAP 파일 시스템에 대한 복제 관계를 생성하여 예기치 않은 재해가 발생할 경우 데이터 손실을 방지합니다. 
---
= 복제 관계를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FSx for ONTAP 파일 시스템에 대한 복제 관계를 생성하여 예기치 않은 재해가 발생할 경우 데이터 손실을 방지합니다.

.이 작업에 대해
복제는 데이터가 상주하는 지역에 재해가 발생하는 경우에 필수적인 추가적인 데이터 보호 계층입니다. 교차 지역 복제를 사용하면 데이터 손실을 방지할 수 있습니다.

이 작업을 수행하면 FSx for ONTAP 파일 시스템에서 하나 또는 모든 소스 볼륨에 대한 복제 관계가 생성됩니다.

타겟 파일 시스템의 복제된 볼륨은 다음과 같은 명명 형식을 `{OriginalVolumeName}_copy`따릅니다.

.시작하기 전에
시작하기 전에 다음 사전 요구 사항을 충족해야 합니다.

* 복제 관계를 생성하려면 스토리지 인벤토리에 두 개의 사용 가능한 파일 시스템이 있어야 합니다.
* 복제 관계에 사용하는 두 파일 시스템에 연결된 링크가 있어야 합니다. 파일 시스템에 기존 링크가 없는 경우 link:create-link.html["먼저 링크를 만듭니다"] link:manage-links.html["링크를 연결합니다"]파일 시스템의 * 계정 이름 * 아래에서 * 연결 링크 * 를 클릭합니다. 링크가 두 파일 시스템에 연결되면 이 작업으로 돌아갑니다.


단일 볼륨을 복제하거나 파일 시스템의 모든 볼륨을 복제하려면 다음 단계를 수행하십시오.

[role="tabbed-block"]
====
.단일 볼륨을 복제합니다
--
.단계
. Workload Factory 콘솔에 로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 복제할 볼륨이 포함된 파일 시스템의 점 3개 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 볼륨 탭에서 복제할 볼륨의 점 3개 메뉴를 선택합니다.
. 데이터 보호 조치 * 를 선택한 다음 * 볼륨 데이터 복제 * 를 선택합니다.
. 복제 생성 페이지의 복제 타겟에서 다음을 제공합니다.
+
.. * FSx for ONTAP 파일 시스템 *: 대상 FSx for ONTAP 파일 시스템에 대한 자격 증명, 지역 및 FSx for ONTAP 파일 시스템 이름을 선택합니다.
.. * 스토리지 VM 이름 *: 드롭다운 메뉴에서 스토리지 VM을 선택합니다.
.. * 볼륨 이름 * : 대상 볼륨 이름은 다음 형식으로 자동으로 `{OriginalVolumeName}_copy`생성됩니다. 자동 생성된 볼륨 이름을 사용하거나 다른 볼륨 이름을 입력할 수 있습니다.
.. * Tiering policy *: 타겟 볼륨에 저장된 데이터에 대한 계층화 정책을 선택합니다.
+
_AUTO_는 Workload Factory FSx for ONTAP 사용자 인터페이스를 사용하여 볼륨을 생성할 때의 기본 계층화 정책입니다. 볼륨 계층화 정책에 대한 자세한 내용은 AWS FSx for NetApp ONTAP 설명서 를 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["볼륨 스토리지 용량"^]참조하십시오.

.. * 최대 전송 속도 *: * 제한 * 을 선택하고 최대 전송 제한(MB/s)을 입력합니다 또는 * 무제한 * 을 선택합니다.
+
제한이 없으면 네트워크 및 애플리케이션 성능이 저하될 수 있습니다. 또는 중요한 워크로드(예: 재해 복구에 주로 사용되는 워크로드)에 FSx for ONTAP 파일 시스템에 대해 무제한 전송 속도를 사용하는 것이 좋습니다.



. Replication settings(복제 설정) 에서 다음을 제공합니다.
+
.. * 복제 간격 *: 소스 볼륨에서 타겟 볼륨으로 스냅샷이 전송되는 빈도를 선택합니다.
.. *장기 보존*: 장기 보존을 위해 스냅샷을 선택적으로 사용할 수 있습니다.
+
장기 보존을 사용하도록 설정한 경우 기존 정책을 선택하거나 새 정책을 생성하여 복제할 스냅샷 및 유지할 스냅샷 수를 정의합니다.

+
... 기존 정책 선택 * 의 경우 드롭다운 메뉴에서 기존 정책을 선택합니다.
... 새 정책 만들기 * 에 다음을 제공합니다.
+
.... * 정책 이름 *: 정책 이름을 입력하십시오.
.... * Snapshot policies *: 표에서 스냅샷 정책 빈도와 유지할 복제본 수를 선택합니다. 두 개 이상의 스냅샷 정책을 선택할 수 있습니다.






. Create * 를 클릭합니다.


--
.파일 시스템의 모든 볼륨을 복제합니다
--
.단계
. Workload Factory 콘솔에 로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP 탭에서 볼륨이 있는 파일 시스템의 점 3개 메뉴를 클릭한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * 복제 생성 * 을 선택합니다.
. 복제 생성 페이지의 복제 타겟에서 다음을 제공합니다.
+
.. * FSx for ONTAP 파일 시스템 *: 대상 FSx for ONTAP 파일 시스템에 대한 자격 증명, 지역 및 FSx for ONTAP 파일 시스템 이름을 선택합니다.
.. * 스토리지 VM 이름 *: 드롭다운 메뉴에서 스토리지 VM을 선택합니다.
.. * 볼륨 이름 * : 대상 볼륨 이름은 다음 형식으로 자동으로 `{OriginalVolumeName}_copy`생성됩니다.
.. * Tiering policy *: 타겟 볼륨에 저장된 데이터에 대한 계층화 정책을 선택합니다.
+
_AUTO_는 Workload Factory FSx for ONTAP 사용자 인터페이스를 사용하여 볼륨을 생성할 때의 기본 계층화 정책입니다. 볼륨 계층화 정책에 대한 자세한 내용은 AWS FSx for NetApp ONTAP 설명서 를 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["볼륨 스토리지 용량"^]참조하십시오.

.. * 최대 전송 속도 *: * 제한 * 을 선택하고 최대 전송 제한(MB/s)을 입력합니다 또는 * 무제한 * 을 선택합니다.
+
제한이 없으면 네트워크 및 애플리케이션 성능이 저하될 수 있습니다. 또는 중요한 워크로드(예: 재해 복구에 주로 사용되는 워크로드)에 FSx for ONTAP 파일 시스템에 대해 무제한 전송 속도를 사용하는 것이 좋습니다.



. Replication settings(복제 설정) 에서 다음을 제공합니다.
+
.. * 복제 간격 *: 소스 볼륨에서 타겟 볼륨으로 스냅샷이 전송되는 빈도를 선택합니다.
.. *장기 보존*: 장기 보존을 위해 스냅샷을 선택적으로 사용할 수 있습니다.
+
장기 보존을 사용하도록 설정한 경우 기존 정책을 선택하거나 새 정책을 생성하여 복제할 스냅샷 및 유지할 스냅샷 수를 정의합니다.

+
... 기존 정책 선택 * 의 경우 드롭다운 메뉴에서 기존 정책을 선택합니다.
... 새 정책 만들기 * 에 다음을 제공합니다.
+
.... * 정책 이름 *: 정책 이름을 입력하십시오.
.... * Snapshot policies *: 표에서 스냅샷 정책 빈도와 유지할 복제본 수를 선택합니다. 두 개 이상의 스냅샷 정책을 선택할 수 있습니다.






. Create * 를 클릭합니다.


--
====
.결과
복제 관계가 * 복제 관계 * 탭에 나타납니다.
