---
sidebar: sidebar 
permalink: create-volume-from-snapshot.html 
keywords: create volume from snapshot, new volume 
summary: BlueXP  워크로드 팩토리에서 FSx for ONTAP 볼륨의 수동 스냅샷을 생성합니다. 스냅샷은 볼륨 컨텐츠의 특정 시점 버전입니다. 
---
= 스냅샷에서 새 FSx for ONTAP 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리의 스냅샷에서 새 FSx for ONTAP 볼륨을 생성하여 시점 복구를 지원합니다.

.이 작업에 대해
스냅샷은 특정 시점에 생성된 FSx for ONTAP 볼륨의 읽기 전용 이미지입니다. 스냅샷에서 새 볼륨을 생성하면 볼륨 크기에 관계없이 몇 초 내에 전체 볼륨의 복사본이 생성됩니다. 새로 생성된 복제본은 새 볼륨을 나타냅니다.

.시작하기 전에
스냅샷에서 볼륨을 생성하기 전에 다음과 같은 제한 사항을 고려하십시오.

* 권한 모델 변경: 이 작업을 사용하여 NAS(Network-Attached Storage) 프로토콜 유형을 전환하는 경우 보안 스타일이 제공하는 권한 모델도 전환할 수 있습니다. 파일 액세스 권한 문제가 발생할 수 있습니다. 이 문제는 권한 설정에 NAS 클라이언트 도구를 사용하여 관리자 액세스 권한으로만 수동으로 해결할 수 있습니다.
* 볼륨 사용량 증가: 스냅샷에서 볼륨을 생성한 후에는 두 개의 독립적인 볼륨이 있고 두 볼륨 모두 호스트 파일 시스템의 용량을 소비합니다.


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 볼륨 스냅샷이 있는 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. 볼륨 탭에서 볼륨을 생성할 스냅샷이 있는 볼륨에 대해 점 3개 메뉴를 선택합니다.
. 데이터 보호 조치 *, * 스냅샷 * 을 선택한 다음 * 스냅샷에서 볼륨 생성 * 을 선택합니다.
. Create volume from a snapshot 대화 상자에서 스냅샷 이름을 입력합니다.
. Create * 를 선택합니다.

