---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: FSx for ONTAP 파일 시스템을 설정한 후 워크로드 팩토리에서 FSx for ONTAP 볼륨을 생성합니다. 
---
= 워크로드 팩토리에서 ONTAP 볼륨에 대한 FSx를 생성합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FSx for ONTAP 파일 시스템을 설정한 후, 워크로드 팩토리에서 FSx for ONTAP 볼륨을 생성하여 데이터를 그룹화하기 위한 가상 리소스로 사용합니다.

.이 작업에 대해
FSx for ONTAP 볼륨은 데이터를 가상으로 그룹화하고, 데이터가 저장되는 방식을 결정하고, 데이터에 대한 액세스 유형을 결정합니다. 볼륨은 파일 시스템 스토리지 용량을 소비하지 않습니다. 볼륨에 저장된 데이터는 주로 SSD 스토리지를 사용합니다. 볼륨의 계층화 정책에 따라 데이터가 용량 풀 스토리지를 사용할 수도 있습니다. 볼륨을 만들 때 볼륨 크기를 설정하고 나중에 크기를 변경할 수 있습니다.

다음 프로토콜을 볼륨에 사용할 수 있습니다.

* CIFS: Windows 운영 체제용 파일 스토리지 프로토콜입니다
* NFS: Unix 운영 체제용 파일 스토리지 프로토콜입니다
* iSCSI: 블록 스토리지 프로토콜


.시작하기 전에
볼륨을 생성하기 전에 다음 사전 요구 사항을 검토하십시오.

* 워크로드 팩토리에 FSx for ONTAP 파일 시스템이 있어야 합니다.
* 스토리지 VM이 있어야 합니다.
* 프로토콜 액세스의 경우 다음을 수행합니다.
+
** 볼륨에 대한 액세스를 구성하려면 다음을 수행해야 link:manage-links.html["링크를 연결합니다"]합니다. 기존 링크가 없는 경우 link:create-link.html["링크를 만듭니다"] 파일 시스템의 링크를 연결하려면 * 계정 이름 * 아래에서 * 링크 * 를 선택합니다. 링크가 연결되면 이 작업으로 돌아갑니다.
** CIFS, NFS 또는 iSCSI 중 선택한 프로토콜에 대한 액세스를 구성해야 합니다.






== 볼륨을 생성합니다

코드상자에서 사용할 수 있는 REST API, CloudFormation 및 Terraform 도구를 사용하여 볼륨을 생성할 수 있습니다. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["자동화를 위해 Codebox를 사용하는 방법을 알아보십시오"^]..


NOTE: Codebox에서 Terraform을 사용할 때 복사하거나 다운로드하는 코드는 숨겨지고 암호가 숨겨집니다. `fsxadmin` `vsadmin` 코드를 실행할 때 암호를 다시 입력해야 합니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 볼륨을 생성할 파일 시스템의 세 점 메뉴를 선택하고 * 볼륨 생성 * 을 선택합니다.
. 볼륨 생성 페이지의 일반 세부 정보 아래에서 다음 세부 정보를 제공합니다.
+
.. * 볼륨 이름 *: 볼륨의 이름을 입력합니다.
.. * 스토리지 VM 이름 *: 필요에 따라 스토리지 VM 이름을 입력합니다.
.. * 볼륨 스타일 *: * FlexVol * 또는 * FlexGroup * 볼륨을 선택합니다.
+
FlexVol 볼륨 스타일이 기본적으로 선택되어 있습니다.

+
FlexGroup 볼륨 크기는 구성 요소의 수에 따라 다릅니다. 구성요소당 100GiB가 필요합니다.

.. * 볼륨 크기 *: 볼륨 크기 및 단위를 입력합니다.
+
선택적으로 볼륨 자동 확장을 활성화합니다. 이 옵션은 볼륨 액세스 유형으로 * 파일 액세스 * 를 선택한 경우 사용할 수 있습니다.

.. *볼륨 자동 증가*: 선택적으로 볼륨 자동 증가 기능을 활성화하여 볼륨 용량이 최대 크기에 도달할 때까지 자동으로 확장되도록 할 수 있습니다. 이 기능은 데이터 사용량 증가에 대응하여 중단 없는 운영을 보장합니다.
+
최대 볼륨 증가 크기와 단위를 지정하세요. 최대 증가 크기는 현재 볼륨 크기보다 작을 수 없습니다.

.. * 태그 * : 선택적으로 최대 50개의 태그를 추가할 수 있습니다.


. Access(연결된 링크가 있는 파일 시스템에만 해당)에서 다음 세부 정보를 제공합니다.
+
.. * 액세스 유형 *: * 파일 액세스 * 또는 * 액세스 차단 * 을 선택합니다. 볼륨 액세스를 구성하는 추가 필드는 선택에 따라 다릅니다.
+
*** * 파일 액세스 *: SMB/CIFS, NFS 또는 이중(SMB/NFS) 프로토콜을 사용하여 권한 있는 여러 사용자와 장치가 볼륨에 액세스할 수 있습니다.
+
볼륨에 대한 파일 액세스를 설정하려면 다음 필드를 완료하십시오.

+
.... * NFS 내보내기 정책 *: NFS 액세스를 제공하기 위해 다음 세부 정보를 제공합니다.
+
..... * 액세스 제어 *: 드롭다운 메뉴에서 * 사용자 지정 내보내기 정책 *, * 기존 내보내기 정책 * 또는 * 볼륨에 대한 액세스 없음 * 을 선택합니다.
..... * 수출 정책 이름 *:
+
사용자 지정 내보내기 정책을 선택한 경우 드롭다운 메뉴에서 기존 정책 이름을 선택합니다.

+
기존 엑스포트 정책을 선택한 경우 새 정책 이름을 입력합니다.

..... * 수출 정책 규칙 추가 *: 필요에 따라 사용자 지정 수출 정책의 경우 수출 정책 규칙을 정책에 추가할 수 있습니다.


.... * cifs share *: 다음을 제공합니다.
+
..... * Name *: SMB 액세스를 제공하려면 CIFS 공유 이름을 입력하십시오.
..... * 권한 *: 모든 권한, 읽기/쓰기, 읽기 또는 권한 없음 을 선택한 다음 세미콜론(;)으로 구분된 사용자 또는 그룹을 입력합니다. 사용자 또는 그룹은 대소문자를 구분하며 사용자 도메인은 "domain\username" 형식을 사용하여 포함되어야 합니다.


.... * 보안 스타일 *: 이중 프로토콜 볼륨의 경우 UNIX 또는 NTFS 보안 스타일을 선택합니다. UNIX는 이중 프로토콜 볼륨의 기본 보안 스타일입니다. 이 컨텍스트에서 사용자 매핑에 대한 자세한 지침은 AWS 블로그 문서를 link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Amazon FSx for NetApp ONTAP으로 멀티프로토콜 워크로드를 지원합니다"^]참조하십시오.


*** * 블록 액세스 *: 중요한 비즈니스 응용 프로그램을 실행하는 호스트가 iSCSI 프로토콜을 사용하여 볼륨에 액세스할 수 있습니다. 파일 시스템 스케일아웃 구축에 HA 쌍 6개 이하가 있는 경우에만 블록 액세스를 사용할 수 있습니다.
+
볼륨에 대한 블록 액세스를 설정하려면 다음 필드를 완료하십시오.

+
.... * iSCSI 구성 *: 볼륨에 대한 블록 액세스를 위해 iSCSI를 구성하려면 다음 세부 정보를 제공하십시오.
+
..... 새 이니시에이터 그룹 생성 * 또는 * 기존 이니시에이터 그룹 매핑 * 을 선택합니다.
..... 드롭다운 메뉴에서 * 호스트 운영 체제 * 를 선택합니다.
..... 새 이니시에이터 그룹에 대해 * 이니시에이터 그룹 이름 * 을 입력합니다.
..... 호스트 이니시에이터 에서 IQN(iSCSI 정규화된 이름) 호스트 이니시에이터를 하나 이상 추가합니다.








. 효율성 및 보호 아래에 다음 세부 정보를 제공합니다.
+
.. *저장소 효율성*: 기본적으로 활성화되어 있습니다. 기능을 비활성화하려면 선택하세요.
+
ONTAP의 중복제거 및 압축 기능을 활용하여 스토리지 효율성을 달성할 수 있습니다. 중복 제거는 중복되는 데이터 블록을 제거합니다. 데이터 압축: 데이터 블록을 압축하여 필요한 물리적 스토리지의 양을 줄입니다.

.. * 변경 불가능한 파일 * : SnapLock라고도 하는 이 기능은 기본적으로 비활성화되어 있습니다. 변경 불가능한 파일을 활성화하면 지정된 기간 동안 데이터가 삭제되거나 덮어써지지 않습니다. 이 기능은 볼륨 생성 중에만 사용할 수 있습니다. 기능이 활성화된 후에는 비활성화할 수 없습니다. 이는 FSx for ONTAP의 프리미엄 기능으로 추가 비용이 부과됩니다. 자세한 내용은 Amazon FSx for NetApp ONTAP 설명서의 을 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["SnapLock 작동 방법"^]참조하십시오.
+
변경 불가능한 파일 기능을 활성화하면 이 볼륨의 파일이 변경 불가능한 WORM(Write-Once-Read-Many) 상태로 영구적으로 커밋됩니다.

+
보존 모드:: 두 가지 보존 모드(_Enterprise_또는_Compliance_)에서 선택할 수 있습니다.
+
--
*** Enterprise_mode, 변경 불가능한 파일 또는 SnapLock에서 관리자는 보존 기간 동안 파일을 삭제할 수 있습니다.
*** Compliance_mode에서는 보존 기간이 만료되기 전에 WORM 파일을 삭제할 수 없습니다. 마찬가지로 볼륨 내의 모든 파일에 대한 보존 기간이 만료될 때까지 변경 불가능한 볼륨을 삭제할 수 없습니다.


--
보존 기간:: 보존 기간에는 _ retention policy_and _ retention perioes _ 라는 두 가지 설정이 있습니다. retention policy_는 변경 불가능한 WORM 상태에서 파일을 보존할 기간을 정의합니다. 사용자 지정 보존 정책을 지정하거나 기본 보존 정책(지정되지 않음)인 30년을 사용할 수 있습니다. 최소 및 최대 보존 기간 _ 은(는) 파일 잠금에 허용되는 시간 범위를 정의합니다.
+
--
참고:: 보존 기간이 만료된 후에도 WORM 파일을 수정할 수 없습니다. WORM 보호만 삭제하거나 새 보존 기간을 설정하여 WORM 보호를 다시 설정할 수 있습니다.


--
자동으로 커밋합니다:: 자동 커밋 기능을 사용하도록 설정할 수 있습니다. 자동 커밋 기능은 파일이 자동 커밋 기간 동안 변경되지 않은 경우 SnapLock 볼륨에서 WORM 상태로 파일을 커밋합니다. 자동 커밋 기능은 기본적으로 비활성화되어 있습니다. 자동 커밋하려는 파일이 SnapLock 볼륨에 있어야 합니다.
볼륨 추가 모드:: WORM 보호 파일에서 기존 데이터를 수정할 수 없습니다. 그러나 변경 불가능한 파일을 사용하면 WORM 추가 가능한 파일을 사용하여 기존 데이터를 계속 보호할 수 있습니다. 예를 들어 증분 데이터를 기록하는 동안 로그 파일을 생성하거나 오디오 또는 비디오 스트리밍 데이터를 유지할 수 있습니다. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["볼륨 추가 모드에 대해 자세히 알아보십시오"^] in Amazon FSx for NetApp ONTAP 설명서.
+
--
.변경 불가능한 파일에 대한 단계
... SnapLock*에서 제공하는 * 변경 불가능한 파일을 활성화하려면 선택합니다.
... 동의하고 계속하려면 상자를 선택합니다.
... 활성화 * 를 선택합니다.
... * 보존 모드 *: * Enterprise * 또는 * Compliance * 모드를 선택합니다.
... * 보존 기간 *:
+
**** 보존 정책 선택:
+
***** * Unspecified *: 보존 정책을 30년으로 설정합니다.
***** * 기간 지정 *: 자신의 보존 정책을 설정할 초, 분, 시간, 일, 월 또는 연도 수를 입력합니다.


**** 최소 및 최대 보존 기간 선택:
+
***** * 최소 *: 최소 보존 기간을 설정할 초, 분, 시간, 일, 개월 또는 연도 수를 입력합니다.
***** * 최대 *: 최대 보존 기간을 설정할 초, 분, 시간, 일, 개월 또는 연도 수를 입력합니다.




... *autocomit*: 자동 커밋을 비활성화하거나 활성화합니다. 자동 커밋을 설정한 경우 자동 커밋 기간을 설정합니다.
... * 볼륨 추가 모드 *: 비활성화 또는 활성화. WORM 파일에 새 콘텐츠를 추가할 수 있습니다.


--


.. * 스냅샷 정책 *: 스냅샷 정책을 선택하여 스냅샷의 빈도와 보존을 지정합니다.
+
다음은 AWS의 기본 정책입니다. 사용자 지정 스냅샷 정책의 경우 링크를 연결해야 합니다.

+
`default`:: 이 정책은 다음 스케줄에 따라 스냅샷을 자동으로 생성하고 가장 오래된 스냅샷 복사본은 새 복제본을 위한 공간을 확보하기 위해 삭제합니다.
+
--
*** 시간당 최대 6개의 스냅샷이 해당 시간 이후 5분 동안 촬영되었습니다.
*** 월요일부터 토요일까지 자정 이후 10분에 최대 2개의 일일 스냅샷을 촬영합니다.
*** 매주 일요일 자정 이후 15분에 최대 2개의 주간 스냅샷이 촬영됩니다.
+

NOTE: 스냅샷 시간은 기본적으로 UTC(협정 세계시)로 설정된 파일 시스템의 시간대를 기준으로 합니다. 시간대 변경에 대한 자세한 내용은 NetApp 지원 설명서의 을 link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["시스템 시간대 표시 및 설정"^] 참조하십시오.



--
`default-1weekly`:: 이 정책은 주간 스케줄에서 스냅샷을 하나만 보존한다는 점을 제외하고 정책과 동일한 방식으로 `default` 작동합니다.
`none`:: 이 정책은 스냅샷을 촬영하지 않습니다. 이 정책을 볼륨에 할당하여 자동 스냅샷이 생성되지 않도록 할 수 있습니다.


.. * Tiering policy *: 볼륨에 저장된 데이터에 대한 계층화 정책을 선택합니다.
+
_Balanced (Auto) _ 는 워크로드 팩토리 콘솔을 사용하여 볼륨을 생성할 때 적용되는 기본 계층화 정책입니다. 볼륨 계층화 정책에 대한 자세한 내용은 AWS FSx for NetApp ONTAP 설명서 를 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["볼륨 스토리지 용량"^] 참조하십시오. 워크로드 팩토리는 계층화 정책을 위해 워크로드 공장 콘솔에서 사용 사례 기반 이름을 사용하며 FSx for ONTAP 계층화 정책 이름을 괄호 안에 포함합니다.



. 고급 구성에서 다음을 제공합니다.
+
.. * Junction path *: 볼륨이 마운트되는 스토리지 VM 네임스페이스의 위치를 입력합니다. 기본 접합 경로는 `/<volume-name>`입니다.
.. * aggregates list *: FlexGroup 볼륨에만 해당됩니다. 애그리게이트를 추가하거나 제거합니다. 최소 애그리게이트 수는 1개입니다.
.. * 구성 요소 수 *: FlexGroup 볼륨에만 해당됩니다. 애그리게이트당 구성요소 수를 입력합니다. 구성요소당 100GiB가 필요합니다.


. Create * 를 선택합니다.


.결과
볼륨 생성이 시작됩니다. 생성된 새 볼륨이 Volumes(볼륨) 탭에 나타납니다.
