---
sidebar: sidebar 
permalink: create-file-system.html 
keywords: create, FSx file system, ONTAP file system, workload factory, storage 
summary: BlueXP  워크로드 팩토리를 사용하여 FSx for ONTAP 파일 시스템을 생성하여 볼륨 및 추가 데이터 서비스를 추가 및 관리할 수 있습니다. 
---
= BlueXP  워크로드 팩토리에서 FSx for ONTAP 파일 시스템을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리를 사용하여 FSx for ONTAP 파일 시스템을 생성하여 볼륨 및 추가 데이터 서비스를 추가 및 관리할 수 있습니다.

.이 작업에 대해
스토리지 VM은 파일 시스템을 생성할 때 생성됩니다.

.시작하기 전에
FSx for ONTAP 파일 시스템을 생성하기 전에 다음이 필요합니다.

* 워크로드 팩토리에게 FSx for ONTAP 파일 시스템을 생성하는 데 필요한 권한을 제공하는 IAM 역할의 ARN link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정에 사용 권한을 부여하는 방법에 대해 알아봅니다"^]..
* ONTAP용 FSx 인스턴스를 생성할 지역 및 VPC 정보




== FSx for ONTAP 파일 시스템을 생성합니다

ONTAP용 FSx 파일 시스템은 _ 빠른 생성 _ 또는 _ 고급 생성 _ 을(를) 사용하여 생성할 수 있습니다. 코드상자에서 사용할 수 있는 REST API, CloudFormation 및 Terraform 도구를 사용할 수도 있습니다. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["자동화를 위해 Codebox를 사용하는 방법을 알아보십시오"^]..


NOTE: Codebox에서 Terraform을 사용할 때 복사하거나 다운로드하는 코드는 숨겨지고 암호가 숨겨집니다. `fsxadmin` `vsadmin` 코드를 실행할 때 암호를 다시 입력해야 합니다.

[role="tabbed-block"]
====
.빠른 생성
--
빠른 생성을 통해 권장되는 모범 사례 구성을 사용할 수 있습니다. FSx for ONTAP 파일 시스템을 생성한 후 대부분의 설정을 변경할 수 있습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 스토리지에서 * FSx for ONTAP 생성 * 을 선택합니다.
. FSx for ONTAP 생성 페이지에서 * 빠른 생성 * 을 선택합니다.
+
저장된 구성을 로드할 수도 있습니다.

. File system general configuration(파일 시스템 일반 구성) 에서 다음을 제공합니다.
+
.. * AWS credentials *: 워크로드 팩토리에 AWS 자격 증명을 추가하거나 자격 증명 없이 계속하려면 선택합니다.
.. * 파일 시스템 이름 *: 파일 시스템의 이름을 입력합니다.
.. * 배포 토폴로지 * : 배포 토폴로지를 선택합니다.
+
*** 스케일 업 토폴로지는 데이터 배포에 하나의 파일 시스템을 사용하며 데이터 증가를 수용하기 위해 크기를 늘릴 수 있는 토폴로지입니다.
*** 스케일아웃 토폴로지는 데이터 배포에 둘 이상의 파일 시스템이 사용되는 지점입니다.


.. * HA 쌍 *: HA 쌍 수를 입력합니다.
+
*** 스케일업 구축의 경우 HA Pair만 있을 수 있습니다.
*** 스케일아웃 구축의 경우 2개~12개의 HA 쌍을 제공합니다.
+
파일 시스템에서 iSCSI 블록 볼륨을 프로비저닝하려면 6개 이하의 HA 쌍을 선택합니다.



.. * 배포 유형 *: 배포 유형을 선택합니다.
+
*** 단일 가용 영역(단일 AZ) 배포: 하드웨어 장애를 모니터링하고 장애 발생 시 인프라 구성 요소를 자동으로 교체하여 가용성을 보장합니다. 가용성 영역 내에서 데이터를 자동으로 복제하여 구성요소 장애로부터 데이터를 보호함으로써 높은 내구성을 제공합니다.
*** 다중 가용 영역(Multi-AZ) 배포: 가용 영역을 사용할 수 없는 경우에도 데이터에 지속적인 가용성을 제공합니다. 다중 AZ 파일 시스템은 단일 AZ 파일 시스템의 모든 가용성 및 내구성 기능을 지원합니다. 다중 AZ 파일 시스템은 공유 ONTAP 파일 데이터에 대한 고가용성이 필요하고 가용 영역 전체에서 기본 복제 기능이 있는 스토리지가 필요한 비즈니스 크리티컬 운영 워크로드를 위해 설계되었습니다.


.. * 태그 * : 선택적으로 최대 50개의 태그를 추가할 수 있습니다.


. Network & security * 아래의 * Region & VPC * 필드에서 파일 시스템의 지역 및 VPC를 선택합니다.
. File system details * 에 다음을 입력합니다.
+
.. * SSD 저장 용량 * : 저장 용량을 입력하고 저장 용량 단위를 선택합니다.
.. * ONTAP 자격 증명 *: ONTAP 사용자 이름과 암호를 입력합니다.
.. * SMB/CIFS 설정 *: 선택 사항. SMB/CIFS 프로토콜을 사용하여 볼륨에 액세스하려는 경우 파일 시스템을 생성하는 동안 스토리지 VM에 대한 Active Directory를 구성해야 합니다. 이 파일 시스템에 대해 생성된 스토리지 VM에 대해 다음 세부 정보를 제공합니다.
+
... * 가입할 Active Directory 도메인 *: Active Directory에 대한 FQDN(정규화된 도메인 이름)을 입력합니다.
... * DNS IP 주소 *: DNS IP 주소를 쉼표로 구분하여 최대 3개까지 입력합니다.
... * SMB 서버 NetBIOS 이름 *: 스토리지 VM에 대해 생성할 Active Directory 컴퓨터 개체의 SMB 서버 NetBIOS 이름을 입력합니다. Active Directory에 있는 이 스토리지 VM의 이름입니다.
... * 사용자 이름 *: 기존 Active Directory에 있는 서비스 계정의 사용자 이름을 입력합니다.
+
도메인 접두사 또는 접미사를 포함하지 마십시오. 의 경우 `EXAMPLE\ADMIN`를 `ADMIN`사용합니다.

... * 비밀번호 *: 서비스 계정의 비밀번호를 입력합니다.
... * 조직 단위 *: 선택적으로 FSx for ONTAP의 컴퓨터 계정을 생성하려는 조직 단위의 이름을 입력합니다. OU는 파일 시스템에 연결할 조직 단위의 고유 경로 이름입니다.
... * 위임된 관리자 그룹 *: 필요에 따라 파일 시스템을 관리할 수 있는 Active Directory의 그룹 이름을 입력합니다.
+
AWS 관리형 Microsoft AD를 사용하는 경우 AWS 위임 FSx 관리자, AWS 위임 관리자 또는 OU에 위임된 권한이 있는 사용자 지정 그룹과 같은 그룹을 지정해야 합니다.

+
자체 관리되는 AD에 가입하는 경우 AD에서 그룹 이름을 사용합니다. 기본 그룹은 `Domain Admins`입니다.





. 정의한 구성을 검토하려면 * Summary * 를 엽니다. 필요한 경우 파일 시스템을 저장하거나 생성하기 전에 설정을 변경할 수 있습니다.
. 파일 시스템을 저장하거나 생성합니다.


파일 시스템을 생성한 경우 * Inventory * 페이지에서 FSx for ONTAP 파일 시스템을 볼 수 있습니다.

--
.고급 만들기
--
Advanced create를 사용하면 가용성, 보안, 백업 및 유지 관리를 포함한 모든 구성 옵션을 설정할 수 있습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 스토리지에서 * FSx for ONTAP 생성 * 을 선택합니다.
. ONTAP용 FSx 생성 페이지에서 * 고급 생성 * 을 선택합니다.
+
저장된 구성을 로드할 수도 있습니다.

. File system general configuration(파일 시스템 일반 구성) 에서 다음을 제공합니다.
+
.. * AWS credentials *: 워크로드 팩토리에 AWS 자격 증명을 추가하거나 자격 증명 없이 계속하려면 선택합니다.
.. * 파일 시스템 이름 *: 파일 시스템의 이름을 입력합니다.
.. * 배포 토폴로지 * : 배포 토폴로지를 선택합니다.
+
*** 스케일 업 토폴로지는 데이터 배포에 하나의 파일 시스템을 사용하며 데이터 증가를 수용하기 위해 크기를 늘릴 수 있는 토폴로지입니다.
*** 스케일아웃 토폴로지는 데이터 배포에 둘 이상의 파일 시스템이 사용되는 지점입니다.


.. * HA 쌍 *: HA 쌍 수를 입력합니다.
+
*** 스케일업 구축의 경우 HA Pair만 있을 수 있습니다.
*** 스케일아웃 구축의 경우 2개~12개의 HA 쌍을 제공합니다.
+
파일 시스템에서 iSCSI 블록 볼륨을 프로비저닝하려면 6개 이하의 HA 쌍을 선택합니다.



.. * 배포 유형 *: 배포 유형을 선택합니다.
+
*** 단일 가용 영역(단일 AZ) 배포: 하드웨어 장애를 모니터링하고 장애 발생 시 인프라 구성 요소를 자동으로 교체하여 가용성을 보장합니다. 가용성 영역 내에서 데이터를 자동으로 복제하여 구성요소 장애로부터 데이터를 보호함으로써 높은 내구성을 제공합니다.
*** 다중 가용 영역(Multi-AZ) 배포: 가용 영역을 사용할 수 없는 경우에도 데이터에 지속적인 가용성을 제공합니다. 다중 AZ 파일 시스템은 단일 AZ 파일 시스템의 모든 가용성 및 내구성 기능을 지원합니다. 다중 AZ 파일 시스템은 공유 ONTAP 파일 데이터에 대한 고가용성이 필요하고 가용 영역 전체에서 기본 복제 기능이 있는 스토리지가 필요한 비즈니스 크리티컬 운영 워크로드를 위해 설계되었습니다.


.. * 태그 * : 선택적으로 최대 50개의 태그를 추가할 수 있습니다.


. 네트워크 및 보안 에서 다음을 제공합니다.
+
.. * 지역 및 VPC *: 파일 시스템의 지역 및 VPC를 선택합니다.
.. * 보안 그룹 *: 기존 보안 그룹을 만들거나 사용합니다.
.. * 가용 영역 *: 가용 영역 및 서브넷을 선택합니다.
+
*** 클러스터 구성 노드 1의 경우: 가용 영역 및 서브넷을 선택합니다.
*** 클러스터 구성 노드 2의 경우: 가용 영역 및 서브넷을 선택합니다.


.. * VPC 경로 테이블 *: VPC 경로 테이블을 선택하여 볼륨에 대한 클라이언트 액세스를 활성화합니다.
.. * 끝점 IP 주소 범위 *: * VPC 외부에 있는 부동 IP 주소 범위를 선택 * 또는 * IP 주소 범위 * 를 입력하고 IP 주소 범위를 입력합니다.
.. * 암호화 * : 드롭다운에서 암호화 키 이름을 선택합니다.


. File system details(파일 시스템 세부 정보) 에서 다음을 제공합니다.
+
.. * SSD 저장 용량 * : 저장 용량을 입력하고 저장 용량 단위를 선택합니다.
.. * 프로비저닝된 IOPS *: * 자동 * 또는 * 사용자 프로비저닝 * 을 선택합니다.
.. * HA 쌍당 처리량 용량 *: HA 쌍당 처리량 용량을 선택합니다.
.. * ONTAP 자격 증명 *: ONTAP 사용자 이름과 암호를 입력합니다.
.. * 스토리지 VM 자격 증명 *: 사용자 이름을 입력합니다. 암호는 이 파일 시스템에 특정하거나 ONTAP 자격 증명에 대해 입력한 것과 동일한 암호를 사용할 수 있습니다.
.. * SMB/CIFS 설정 *: 선택 사항. SMB/CIFS 프로토콜을 사용하여 볼륨에 액세스하려는 경우 파일 시스템을 생성하는 동안 스토리지 VM에 대한 Active Directory를 구성해야 합니다. 이 파일 시스템에 대해 생성된 스토리지 VM에 대해 다음 세부 정보를 제공합니다.
+
... * 가입할 Active Directory 도메인 *: Active Directory에 대한 FQDN(정규화된 도메인 이름)을 입력합니다.
... * DNS IP 주소 *: DNS IP 주소를 쉼표로 구분하여 최대 3개까지 입력합니다.
... * SMB 서버 NetBIOS 이름 *: 스토리지 VM에 대해 생성할 Active Directory 컴퓨터 개체의 SMB 서버 NetBIOS 이름을 입력합니다. Active Directory에 있는 이 스토리지 VM의 이름입니다.
... * 사용자 이름 *: 기존 Active Directory에 있는 서비스 계정의 사용자 이름을 입력합니다.
+
도메인 접두사 또는 접미사를 포함하지 마십시오. 의 경우 `EXAMPLE\ADMIN`를 `ADMIN`사용합니다.

... * 비밀번호 *: 서비스 계정의 비밀번호를 입력합니다.
... * 조직 단위 *: 선택적으로 FSx for ONTAP의 컴퓨터 계정을 생성하려는 조직 단위의 이름을 입력합니다. OU는 파일 시스템에 연결할 조직 단위의 고유 경로 이름입니다.
... * 위임된 관리자 그룹 *: 필요에 따라 파일 시스템을 관리할 수 있는 Active Directory의 그룹 이름을 입력합니다.
+
AWS 관리형 Microsoft AD를 사용하는 경우 AWS 위임 FSx 관리자, AWS 위임 관리자 또는 OU에 위임된 권한이 있는 사용자 지정 그룹과 같은 그룹을 지정해야 합니다.

+
자체 관리되는 AD에 가입하는 경우 AD에서 그룹 이름을 사용합니다. 기본 그룹은 `Domain Admins`입니다.





. 백업 및 유지 관리에서 다음을 제공합니다.
+
.. * ONTAP용 FSx 백업 *: 매일 자동 백업이 기본적으로 활성화됩니다. 필요한 경우 비활성화하십시오.
+
... * 자동 백업 보존 기간 *: 자동 백업을 유지할 일 수를 입력합니다.
... * 일일 자동 백업 윈도우 *: * 기본 설정 없음 * (일일 백업 시작 시간이 선택됨) 또는 * 일일 백업 시작 시간 선택 * 을 선택하고 시작 시간을 지정합니다.
... * 주별 유지 보수 윈도우 *: * 기본 설정 없음 * (주별 유지 보수 윈도우 시작 시간이 선택됨) 또는 * 30분 주별 유지 보수 윈도우 시작 시간 선택 * 을 선택하고 시작 시간을 지정합니다.




. 파일 시스템을 저장하거나 생성합니다.


파일 시스템을 생성한 경우 * Inventory * 페이지에서 FSx for ONTAP 파일 시스템을 볼 수 있습니다.

--
====
.다음 단계
스토리지 인벤토리에 파일 시스템을 사용하면 FSx for ONTAP 파일 시스템을 관리하고 리소스를 설정할 수 있습니다 link:create-volume.html["볼륨 생성"] link:data-protection-overview.html["데이터 보호"] .
