---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, inodes management, file system capacity 
summary: 이 기능을 활성화하면 Workload Factory가 시간이 지남에 따라 용량 요구 사항이 변경됨에 따라 FSx for ONTAP 파일 시스템에 증분 스토리지나 inode를 자동으로 추가할 수 있습니다. 
---
= 파일 시스템에 대한 자동 용량 및 inode 관리 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
자동 용량 및 inode 관리를 활성화하면 NetApp Workload Factory 시간이 지남에 따라 용량 요구 사항이 변경됨에 따라 FSx for ONTAP 파일 시스템에 증분 스토리지 또는 inode를 자동으로 추가할 수 있습니다.  또한, 이 기능을 활성화하면 용량과 inode를 수동으로 모니터링할 필요가 없습니다.



== 이 작업에 대해

FSx for ONTAP 파일 시스템 검사는 30분마다 수행되어 증분 스토리지를 추가해야 하는지 여부를 확인하고 사용 가능한 볼륨 inode, 볼륨의 최대 파일 및 폴더 수를 확인하여 구성된 자동 용량 관리 임계값에 따라 해당 수가 증가하도록 합니다.

한 계정에서만 이 기능을 관리할 수 있습니다.

모든 FSx for ONTAP 파일 시스템의 최대 SSD 스토리지 용량은 524,288GiB입니다. 할당량 증가를 요청하려면 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["할당량"^] AWS FSx for NetApp ONTAP 설명서 를 참조하십시오.



== 자동 용량 관리 활성화

FSx for ONTAP 파일 시스템의 최대 크기 한도까지 증분 스토리지를 자동으로 추가하려면 자동 용량 관리를 활성화합니다.

.시작하기 전에
시작하기 전에 다음 사항을 고려하십시오.

* 당신은해야합니다link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["_view, planning, and analysis_ 권한 정책으로 자격 증명을 부여합니다."^] 이 작업을 완료하려면 Workload Factory로 이동하세요.
* 볼륨 inode가 저장 용량과 함께 증가하도록 하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."].. 링크가 연결되면 이 작업으로 돌아갑니다.
* AWS는 SSD 용량 증가 시 최소 6시간의 쿨다운 기간을 적용하므로 데이터 마이그레이션 중에는 이 기능을 활성화하지 마십시오. 이 제한으로 인해 조정이 지연될 수 있으므로, 이에 따라 계획을 세우십시오.


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 저장소 타일에서 *저장소로 이동*을 선택합니다.
. 저장소 메뉴에서 *FSx for ONTAP*를 선택합니다.
. *FSx for ONTAP*에서 자동 용량 관리를 활성화할 파일 시스템의 작업 메뉴를 선택합니다.
. 관리 * 를 선택합니다.
. 정보 아래에서 * 자동 용량 관리 * 옆에 있는 연필 아이콘을 선택합니다. 마우스를 * 자동 용량 관리 * 행 위로 이동하면 연필 아이콘이 드롭다운 화살표 옆에 표시됩니다.
. 자동 용량 관리 * 대화 상자에서 다음을 제공합니다.
+
.. * 자격 증명 *: 드롭다운 메뉴에서 _AUTOMATE_PERTIONS를 사용하여 자격 증명을 선택합니다.
.. 활성화 버튼을 선택하여 * 자동 용량 관리 활성화 * 를 선택합니다.
+
또는 이 기능을 비활성화합니다. 파일 시스템 용량을 늘려야 하는 경우 먼저 자동 용량 관리를 해제해야 합니다.

.. *경고 임계값*: Workload Factory 알림 서비스에서 알림을 트리거하려면 경고 임계값을 임계값 증가보다 낮게 설정합니다.  기본값은 70%입니다.
+
경고 임계값 설정은 다음 경우에만 사용할 수 있습니다.link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Workload Factory 알림 서비스를 활성화했습니다."^] .

.. *임계값 증가*: FSx for ONTAP 파일 시스템의 최대 백분율 증가를 입력합니다.  기본값은 80%입니다.
+
이는 Workload Factory가 용량을 늘리기 위해 작업을 트리거하는 임계값입니다.  예를 들어, 파일 시스템 용량이 80%에 도달하면 Workload Factory는 용량을 늘립니다.

.. *증분 증가*: 용량을 점진적으로 늘릴 백분율을 입력합니다.  기본값은 10%입니다.
+
이는 임계값에 도달할 때마다 용량을 늘리는 비율입니다.  예를 들어, 파일 시스템이 80% 채워져 있고 증분 증가가 10%로 설정된 경우 Workload Factory는 용량을 10% 늘립니다.



. Apply * 를 선택합니다.


.결과
파일 시스템에 추가 용량이 필요한지 확인하기 위해 30분마다 파일 시스템 검사가 수행됩니다.



== 자동 inode 관리 활성화

자동 inode 관리를 활성화하여 허용 가능한 한도까지 inode(파일) 수를 늘려 볼륨당 파일 용량이 확장되도록 합니다.


NOTE: *Terraform 사용자*: Terraform에는 모든 작업이 Terraform 내에서 완료되어야 한다는 제한이 있습니다.  Terraform에서는 inode 관리가 지원되지 않지만 Workload Factory 콘솔에서 자동 inode 관리를 활성화할 수 있습니다.

.시작하기 전에
시작하기 전에 다음 사항을 고려하십시오.

* 볼륨 inode를 자동으로 관리하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."]. 링크가 연결되면 이 작업으로 돌아갑니다.
* 자동 inode 관리에는 Workload Factory 알림 서비스에서 알림을 트리거하는 _경고 임계값_을 설정할 수 있습니다.  이 기능을 사용하려면 다음이 필요합니다.link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Workload Factory 알림 서비스 활성화"^] 첫 번째.
* 당신은해야합니다link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["_view, planning, and analysis_ 권한 정책으로 자격 증명을 부여합니다."^] 이 작업을 완료하려면 Workload Factory로 이동하세요.


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 저장소 타일에서 *저장소로 이동*을 선택합니다.
. 저장소 메뉴에서 *FSx for ONTAP*를 선택합니다.
. *FSx for ONTAP*에서 파일 시스템의 작업 메뉴를 선택하여 자동 inode 관리를 활성화합니다.
. 관리 * 를 선택합니다.
. 정보에서 *자동 inode 관리* 옆에 있는 연필 아이콘을 선택합니다.  마우스를 *자동 inode 관리* 행 위에 올려 놓으면 드롭다운 화살표 옆에 연필 아이콘이 나타납니다.
. *자동 inode 관리* 대화 상자에서 다음을 제공합니다.
+
.. * 자격 증명 *: 드롭다운 메뉴에서 _AUTOMATE_PERTIONS를 사용하여 자격 증명을 선택합니다.
.. *자동 inode 관리 활성화*를 위해 활성화 버튼을 선택하세요.
+
또는 해당 기능을 비활성화하세요.  inode 수를 늘려야 하는 경우 먼저 자동 inode 관리를 비활성화해야 합니다.

.. *경고 임계값*: Workload Factory 알림 서비스에서 알림을 트리거하려면 경고 임계값을 임계값 증가보다 낮게 설정합니다.  기본값은 70%입니다.
+
경고 임계값 설정은 다음 경우에만 사용할 수 있습니다.link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Workload Factory 알림 서비스를 활성화했습니다."^] .

.. *임계값 증가*: 볼륨당 inode(파일) 수의 최대 백분율 증가를 입력합니다.  기본값은 80%입니다.
.. *증분적 증가*: inode(파일) 수를 점진적으로 늘릴 백분율을 입력합니다.  기본값은 10%입니다.


. Apply * 를 선택합니다.


.결과
볼륨에 볼륨당 추가 inode(파일)가 필요한지 확인하기 위해 30분마다 파일 시스템 검사가 수행됩니다.
