---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: 이 기능을 활성화하면 워크로드 팩토리에서 시간이 지남에 따라 용량 요구사항이 변경되면 FSx for ONTAP 파일 시스템에 증분 스토리지를 자동으로 추가할 수 있습니다. 
---
= FSx for ONTAP 파일 시스템에 대한 자동 용량 관리 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
이 기능을 활성화하면 BlueXP  워크로드 팩토리에서 시간이 지남에 따라 용량 요구사항이 변경될 경우 FSx for ONTAP 파일 시스템에 증분 스토리지를 자동으로 추가할 수 있습니다.

.이 작업에 대해
한 계정에서만 이 기능을 관리할 수 있습니다.

모든 FSx for ONTAP 파일 시스템의 최대 SSD 스토리지 용량은 524,288GiB입니다. 할당량 증가를 요청하려면 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["할당량"^] AWS FSx for NetApp ONTAP 설명서 를 참조하십시오.

.시작하기 전에
이 작업을 완료하려면 작업 부하 공장에서 _automate_permissions 에 대한 자격 증명이 있어야 합니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to Storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 파일 시스템의 세 점 메뉴를 선택하여 의 자동 용량 관리를 활성화합니다.
. 관리 * 를 선택합니다.
. 정보 아래에서 * 자동 용량 관리 * 옆에 있는 연필 아이콘을 선택합니다. 마우스를 * 자동 용량 관리 * 행 위로 이동하면 연필 아이콘이 드롭다운 화살표 옆에 표시됩니다.
. 자동 용량 관리 * 대화 상자에서 다음을 제공합니다.
+
.. * 자격 증명 *: 드롭다운 메뉴에서 _AUTOMATE_PERTIONS를 사용하여 자격 증명을 선택합니다.
.. 활성화 버튼을 선택하여 * 자동 용량 관리 활성화 * 를 선택합니다.
+
또는 이 기능을 비활성화합니다. 파일 시스템 용량을 늘려야 하는 경우 먼저 자동 용량 관리를 해제해야 합니다.

.. * 용량 임계값 *: FSx for ONTAP 파일 시스템의 최대 크기를 입력합니다.
.. * 용량 증가 증분 *: 용량을 점진적으로 증가시키는 비율을 입력합니다.


. Apply * 를 선택합니다.

