---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: BlueXP  Workload Factory for Databases는 Microsoft SQL Server 구성을 스캔하여 운영 효율성을 높이는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= 잘 설계된 파일 시스템 구성 구현
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
구성 분석 통찰력과 권장 사항을 활용하여 워크로드 팩토리를 활용하여 FSx for ONTAP 파일 시스템에 대한 모범 사례를 구현하세요. 잘 설계된 상태를 쉽게 검토하고, 구성 관련 문제를 파악하고, 안정성, 보안, 효율성, 성능 및 비용 측면에서 최적화되지 않은 시스템의 아키텍처를 개선하기 위한 조치를 취할 수 있습니다.

link:configuration-analysis.html["워크로드 팩토리의 구성 분석과 잘 설계된 상태에 대해 알아보세요."]

.이 작업에 대해
Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 배포 구성을 매일 분석합니다. 일일 분석은 잘 설계된 상태, 통찰력 및 권장 사항과 함께 파일 시스템이 모범 사례를 충족하도록 구성 문제를 자동으로 해결하는 옵션을 제공합니다.

워크로드 팩토리 콘솔 내의 스토리지 인벤토리에서 파일 시스템의 구성 문제에 대한 권장 사항을 검토하고 문제를 해결할 수 있는 옵션이 있습니다.

분석 대상:: 워크로드 공장에서 FSx for ONTAP 파일 시스템에 대한 다음 구성의 체계적으로 설계된 상태를 분석합니다.
+
--
* SSD 용량 임계값입니다
* 데이터 계층화
* 예약된 로컬 스냅샷
* ONTAP 백업을 위한 FSx
* 원격 데이터 복제
* 스토리지 효율성
* 자동 용량 관리


--


.시작하기 전에
* _읽기 전용_ 또는 _읽기/쓰기_ 권한이 있는 자격 증명이 있어야 합니다. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정에서 사용 권한을 부여하는 방법에 대해 알아봅니다"^]..
* 설정이나 구성을 수정하기 전에 각 권장 사항을 주의 깊게 검토하십시오.



NOTE: 해결 프로세스로 인해 인스턴스 다운타임이나 서비스 중단이 발생할 수 있습니다. 구성 문제를 해결하기 전에 권장 사항을 주의 깊게 검토하십시오.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 데이터베이스 타일에서 * 저장소 인벤토리로 이동 * 을 선택합니다.
. FSx for ONTAP * 탭에서 * 제대로 구성된 상태 * 열로 이동하여 파일 시스템에서 수정할 문제를 선택합니다.
. 잘 설계된 파일 시스템의 대시보드에서 구성 문제를 범주, 하위 범주, 상태, 심각도 및 태그로 필터링합니다.
. 드롭다운 화살표를 선택하여 모든 구성에 대한 권장 사항을 확인합니다. 권장 사항을 주의 깊게 검토하십시오.
+
이 권장 사항에서는 최적화되지 않은 구성의 모범 사례와 잠재적 위험을 설명합니다.

. 수정 * 을 선택합니다.
+
View and fix * 가 옵션으로 제공되는 경우 수정할 영향을 받는 볼륨을 선택합니다.

. 대화 상자에 나타나는 요약 및 작업 항목을 검토하여 문제 해결을 선택한 경우 어떤 일이 발생할지 알아봅니다. 일부 작업으로 인해 인스턴스 다운 시간 또는 서비스 중단이 발생할 수 있습니다.
. 구성 문제를 해결하려면 * 계속 * 을 선택하십시오.


.결과
문제 해결 프로세스가 시작됩니다. 계정 설정 메뉴를 선택한 다음 *추적기*를 선택하여 작업 상태를 확인하세요.
