---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: adjust capacity, elastic file system capacity, increase file system capacity, increase FSx capacity, decrease file system capacity, decrease FSx capacity 
summary: 다양한 활성 작업 세트가 포함된 프로젝트 기반 워크로드의 요구 사항을 충족하기 위해 FSx for ONTAP 파일 시스템의 SSD 스토리지 용량을 수동으로 조정합니다. 
---
= 워크로드 팩토리에서 파일 시스템 용량 조정
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
다양한 활성 작업 세트가 포함된 프로젝트 기반 워크로드의 요구 사항을 충족하도록 FSx for ONTAP 파일 시스템의 SSD(솔리드 스테이트 드라이브) 저장 용량을 수동으로 조정합니다.

사용된 SSD 저장 용량이 지정한 임계값을 초과하면 FSx for ONTAP 파일 시스템의 SSD 저장 용량을 늘리고, 작업 세트가 비활성 상태일 때는 SSD 저장 용량을 줄여 비용 효율성을 개선합니다.

또는 워크로드 팩토리에서 파일 시스템 용량을 관리하도록 할 수 link:enable-auto-capacity-management.html["자동 용량 관리 기능을 활성화합니다"]있습니다.


NOTE: SSD 저장 용량 감소는 2세대 파일 시스템에서만 지원됩니다.

.이 작업에 대해
탄력적인 파일 시스템 용량을 사용하면 작업 부하 요구 사항에 맞게 파일 시스템 용량을 동적으로 조정할 수 있습니다.

파일 시스템 용량을 조정하면 FSx for ONTAP 파일 시스템의 IOPS에 영향을 미칩니다.

자동으로link:provision-iops.html["IOPS 프로비저닝"] 파일 시스템의 경우 SSD 용량이 1GiB 증가하거나 감소할 때마다 IOPS는 3 IOPS씩 증가하거나 감소합니다.

link:provision-iops.html["IOPS 프로비저닝"]수동으로 증가하는 파일 시스템 용량을 지원하기 위해 IOPS 할당을 늘려야 할 수 있습니다.

SSD 스토리지 용량 제한에 대해서는 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["할당량"^] AWS FSx for NetApp ONTAP 설명서를 참조하십시오.

.시작하기 전에
파일 시스템의 용량을 조정하려면 먼저 다음을 수행해야 합니다.link:enable-auto-capacity-management.html["자동 용량 관리를 비활성화합니다"] .

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to Storage inventory * 를 선택합니다.
. 대시보드에서 *SSD 용량 조정*을 선택합니다.
. 용량을 조정할 파일 시스템을 선택한 다음 *계속*을 선택합니다.
+
*잠재적 절감*은 용량을 줄이는 것에 대한 권장 사항입니다.

. SSD 용량 조정 대화 상자에서 *프로비저닝된 용량*에 대한 숫자를 입력합니다.
. 프로비저닝된 용량의 단위를 선택합니다.
. Apply * 를 선택합니다.

