---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 
---
= Amazon FSx for NetApp ONTAP의 알려진 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== 지역 지원

다음 AWS 지역은 지원되지 않습니다.

* 중국 지역
* GovCloud(미국) 지역
* 시크릿 클라우드
* 극비 클라우드




== HA 쌍 추가 제한

* 이 작업을 완료하는 데 약 30분 정도 걸릴 수 있습니다.
* HA 쌍을 추가하면 HA 쌍 추가, IOPS 프로비저닝, SSD 용량 증가, 처리량 용량 업데이트 등과 같은 작업이 제한됩니다.




== 처리량 용량 영역 지원



=== 스케일업 배포

스케일 업 구성은 모든 지역에서 최대 2GB/s까지 지원됩니다. 다음 지역에서는 스케일업 배포를 위해 최대 4GB/s의 처리 용량을 지원합니다. US East(Ohio) Region, US East(N. Virginia) Region, US West(Oregon) Region, Europe(Ireland).



=== 스케일아웃 구축

다음 지역은 확장형 배포에 대해 최대 6GB/s의 처리량 용량을 지원합니다. 미국 동부(버지니아 북부 및 오하이오), 미국 서부(캘리포니아 북부 및 오리건), 유럽(프랑크푸르트, 아일랜드 및 스톡홀름), 아시아 태평양(싱가포르 및 시드니).



== 용량 관리

* 볼륨 자동 확장 기능은 현재 iSCSI 프로토콜에 대해 지원되지 않습니다.
* 자동 용량 관리 기능이 실행 중일 때는 수동으로 용량을 늘릴 수 없습니다.
* 자동 용량 관리 기능을 비활성화하는 것은 사용 권한과 동일한 사용 권한으로만 가능합니다.
* 자동 용량 관리가 활성화된 경우 볼륨 inode가 스토리지 용량과 함께 늘어나도록 하는 링크가 필요합니다.




== 스토리지 VM

SKU당 저장 VM의 수는 제한되어 있습니다.  Workload Factory에서는 제한을 넘어서는 스토리지 VM 생성이 지원되지 않습니다.^1^

파일 시스템당 최대 SVM 수는 AWS 설명서의 을 참조하십시오 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["FSx for ONTAP 스토리지 가상 머신 관리"^] .



== iSCSI 프로토콜 지원

* iSCSI 프로토콜은 FlexVol 볼륨에만 사용할 수 있습니다. ^1^
* 볼륨당 하나의 LUN만 구성할 수 있습니다.
* iSCSI 볼륨에서는 볼륨 크기 감소가 지원되지 않습니다.




== 데이터 보호

* 스냅샷을 삭제할 수 없습니다.
* 파일 시스템을 복제할 때 파일 시스템의 모든 볼륨이 동일한 복제 정책을 사용합니다.
* 장기 보존 복제 관계의 경우 마지막 스냅샷만 복구에 사용할 수 있습니다.
* 다음 기능은 변경 불가능한 스냅샷에서 지원되지 않습니다.
+
** 정합성 보장 그룹
** FabricPool
** FlexCache 볼륨
** SMTape
** SnapMirror 활성 동기화
** schedule 매개 변수를 사용하는 SnapMirror 정책 규칙입니다
** SnapMirror 동기식
** SVM 데이터 이동성(소스 클러스터에서 타겟 클러스터로 SVM을 마이그레이션 또는 재배치하는 데 사용)






== 스토리지 비용 절감 계산기

Storage Savings Calculator는 다음 구성에 대한 비용 절감액을 계산하지 않습니다.

* FSx for Windows 파일 서버: HDD 스토리지 유형
* EBS(Elastic Block Store): st1, SC1 및 표준 볼륨 유형
* EFS(Elastic File System): 처리량 증가 모드입니다




== 시스템 관리자

System Manager는 FSx for ONTAP 연결을 위한 링크를 지원하지 않습니다.



== AWS Secrets Manager 지원

콘솔 에이전트를 사용하는 경우 AWS Secrets Manager는 지원되지 않습니다.

참고:

. Amazon FSx for NetApp ONTAP에 적용됩니다

