---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: Amazon FSx for NetApp ONTAP은 고객이 워크로드 공장 내에서 워크로드의 스토리지 백엔드로 파일 시스템을 시작하고 실행할 수 있는 완전 관리형 서비스입니다. 
---
= BlueXP  워크로드 공장 에서 Amazon FSx for NetApp ONTAP에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSx for NetApp ONTAP는 완전 관리형 클라우드 기반 데이터 스토리지 서비스로서, 고급 데이터 관리 기능과 확장성이 뛰어난 성능을 제공합니다. FSx for ONTAP을 사용하면 BlueXP  워크로드 공장 내의 모든 워크로드에 대한 스토리지 백엔드로 파일 시스템을 생성하고 관리할 수 있습니다.

ONTAP용 FSX는 NetApp 고객이 현재 사내에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 기본 AWS 서비스의 단순성, 민첩성, 보안 및 확장성으로 제공합니다.

FSx for ONTAP은 워크로드 팩토리의 _ 스토리지 _ 구성 요소입니다.



== 피처

FSx for ONTAP은 다음과 같은 기능을 제공합니다.

* * 완전 관리형 서비스 *: 워크로드 팩토리 콘솔과 통합된 완전 관리형 서비스를 제공합니다.
* * 고가용성 *: 각 FSx for ONTAP 파일 시스템에 고가용성을 제공하여 단일 및 다중 가용성 영역 배포를 지원합니다.
* * 자동 스냅샷 *: 파일 시스템 또는 볼륨의 거의 즉각적이고 공간 효율적인 시점 읽기 전용 복사본인 자동화된 효율적인 스냅샷으로 데이터를 보호합니다.
* * 볼륨 복제 *: Amazon Web Services의 교차 지역 복제를 통해 재해 복구를 제공합니다.
* * 효율적인 백업 *: 비상 시 다른 지역에 있는 데이터의 복사본을 사용하여 보호 계층을 추가합니다.
* * 빠른 복제 *: 빠른 복제를 통해 애플리케이션 개발 가속화
* * 다중 프로토콜 지원 *: NFS(네트워크 파일 시스템), SMB(서버 메시지 블록) 및 iSCSI(인터넷 소형 컴퓨터 시스템 인터페이스) 프로토콜을 지원합니다.
* * 높은 처리량 *: FSx for ONTAP 파일 시스템에서 실행되는 워크로드의 지연 시간을 줄여 높은 처리량 성능을 제공합니다.
* * 인메모리 캐시 및 NVMe 캐시 *: 고유한 인메모리 캐시와 NVMe 캐시를 포함하고 있어 자주 액세스되는 데이터의 성능을 향상시킵니다.
* * 수십만 IOPS *: SSD 디스크와 함께 수십만 IOPS를 제공하여 스토리지와 워크로드가 적시에 결과를 얻을 수 있도록 보장합니다.
* * Thin Provisioning *: 용량을 미리 프로비저닝할 수 있으므로 용량이 더 필요할 때까지 비용을 절감할 수 있습니다.
* * 데이터 중복제거 및 압축 *: 중복 데이터를 제거하고 데이터를 압축하여 FSx for ONTAP 파일 시스템에 필요한 물리적 스토리지의 양을 줄임으로써 비용을 절감합니다.
* * 데이터 계층화 *: 액세스 빈도가 낮은 데이터를 운영 고성능 SSD 스토리지 계층에서 보조 용량 풀 스토리지 계층으로 이동하여 스토리지 비용을 절감할 수 있습니다.




== 워크로드 팩토리의 추가 기능

* * 스토리지 비용 비교 계산기 *: Amazon EBS(Elastic Block Store), EFS(Elastic File System) 및 FSx for Windows 파일 서버 스토리지 비용을 FSx for ONTAP와 비교합니다. 계산기에서 FSx for ONTAP 스토리지 구성이 어떻게 잠재적 비용 절감을 제공하는지 살펴보고 FSx for ONTAP 스토리지로의 마이그레이션을 계획하실 수 있습니다.
* * Workload Factory 사용자 인터페이스 *: Quick create_and_Advanced create_deployment 모드 옵션을 제공합니다. 빠른 생성에는 스토리지 구성에 대한 AWS, NetApp 및 업계 표준 모범 사례가 포함됩니다.
* * Codebox *: 개발자에게 FSx for ONTAP 작업을 위한 코드 뷰어, 복사 및 다운로드용 코드 템플릿, 코드 재사용을 위한 자동화 카탈로그를 제공합니다.




== 워크로드 팩토리 사용을 위한 툴

다음 툴과 함께 BlueXP  워크로드 팩토리를 사용할 수 있습니다.

* * 워크로드 팩토리 콘솔 * : 워크로드 팩토리 콘솔은 애플리케이션과 프로젝트에 대한 시각적이고 포괄적인 뷰를 제공합니다.
* * BlueXP  콘솔 *: BlueXP  콘솔은 하이브리드 인터페이스 환경을 제공하므로 다른 BlueXP  서비스와 함께 BlueXP  워크로드 팩토리를 사용할 수 있습니다.
* * 질문하기 *: 질문하기 AI 도우미를 사용하여 워크로드 팩토리 웹 UI를 벗어나지 않고도 워크로드 공장에 대해 자세히 알아보십시오. 워크로드 기본 도움말 메뉴에서 질문하기 에 액세스합니다.
* * CloudShell CLI *: 워크로드 팩토리에는 단일 브라우저 기반 CLI를 통해 모든 계정에서 AWS 및 NetApp 환경을 관리하고 운영할 수 있는 CloudShell CLI가 포함되어 있습니다. 워크로드 팩토리 콘솔의 상단 표시줄에서 CloudShell에 액세스합니다.
* * REST API *: 워크로드 팩토리 REST API를 사용하여 FSx for ONTAP 파일 시스템 및 기타 AWS 리소스를 배포하고 관리합니다.
* * CloudFormation *: AWS CloudFormation 코드를 사용하여 AWS 계정의 CloudFormation 스택에서 AWS 및 타사 리소스를 모델링, 프로비저닝 및 관리하기 위해 워크로드 팩토리 콘솔에 정의한 작업을 수행합니다.
* * Terraform BlueXP  워크로드 팩토리 공급자 *: Terraform을 사용하여 워크로드 팩토리 콘솔에서 생성된 인프라 워크플로우를 구축하고 관리하십시오.




== 비용

AWS는 워크로드 팩토리가 아닌 FSx for ONTAP 계정을 유지 관리합니다. 을 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Amazon FSx for NetApp ONTAP 가격"^]참조하십시오.



== 지역

워크로드 팩토리는 FSx for ONTAP 이 지원되는 모든 상업 지역에서 지원됩니다.link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 아마존 지역을 봅니다."^]

다음 AWS 지역은 지원되지 않습니다.

* 중국 지역
* GovCloud(미국) 지역
* 시크릿 클라우드
* 극비 클라우드




== 도움말 보기

NetApp ONTAP용 Amazon FSx는 AWS 퍼스트 파티 솔루션입니다. 이 서비스를 사용하는 FSx for ONTAP 파일 시스템, 인프라 또는 솔루션과 관련하여 궁금한 사항이나 기술 지원 문제가 있는 경우 AWS 관리 콘솔의 지원 센터를 사용하여 AWS에 지원 케이스를 여십시오. “FSx for ONTAP” 서비스와 적절한 범주를 선택합니다. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공합니다.

작업 부하 공장 또는 작업 부하 공장 애플리케이션 및 서비스에 대한 일반적인 질문은 을 참조하십시오link:get-help.html["워크로드 팩토리용 FSx for ONTAP에 대한 도움을 받으십시오"].
