---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: 워크로드 팩토리 링크는 워크로드 공장 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간의 신뢰 관계 및 연결을 생성합니다. 
---
= BlueXP  워크로드 공장 링크에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리 링크는 워크로드 공장 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간의 신뢰 관계와 연결을 생성합니다. 따라서 Amazon FSx for ONTAP API를 통해 사용할 수 없는 ONTAP REST API 호출에서 직접 특정 파일 시스템 기능을 모니터링하고 관리할 수 있습니다.

워크로드 팩토리부터 시작하는 데 필요한 링크는 없지만, 경우에 따라 모든 워크로드 팩토리 기능 및 워크로드 기능의 잠금을 해제하기 위한 링크를 만들어야 할 수도 있습니다.



== 링크 작동 방법

링크 활용 AWS Lambda. Lambda는 이벤트에 대한 응답으로 코드를 실행하고 해당 코드에 필요한 컴퓨팅 리소스를 자동으로 관리합니다. 생성하는 링크는 NetApp 계정의 일부이며 AWS 계정과 연결됩니다.

링크를 생성한 후 하나 이상의 FSx for ONTAP 파일 시스템에 연결할 수 있습니다. 각 파일 시스템은 동일한 NetApp 계정에 있는 하나의 링크에만 연결할 수 있습니다. NetApp 계정이 여러 개인 경우 단일 파일 시스템을 다른 NetApp 계정 아래의 추가 링크에 연결할 수 있습니다.

워크로드 팩토리의 FSx for ONTAP 파일 시스템 페이지에서 링크를 생성할 수 있습니다. link:create-link.html["링크를 만드는 방법에 대해 알아봅니다"] 를 참조하십시오.



== 비용

Lambda가 수행하는 각 트랜잭션마다 요금이 발생합니다. Lambda는 두 시스템 사이에서 프록시 역할을 하기 때문에 Lambda가 파일 시스템의 ONTAP REST API에 요청을 전송하고 해당 응답을 워크로드 공장으로 다시 전송하는 경우 비용이 청구됩니다.

link:https://aws.amazon.com/lambda/pricing/["AWS Lambda 사용과 관련된 비용에 대해 자세히 알아보십시오"^]



== 링크가 필요한 경우

워크로드 팩토리에는 일부 정보를 표시하고 일부 작업을 수행하기 위한 링크가 필요합니다. 연결이 필요한 작업을 수행하려고 하는데 FSx for ONTAP 파일 시스템에 링크가 연결되지 않은 경우 작업에 링크가 필요하다는 메시지가 표시됩니다. 이때 새 링크를 추가하거나 FSx for ONTAP 파일 시스템을 기존 링크와 연결하여 작업을 수행할 수 있습니다.

링크가 필요한 기능은 다음과 같습니다.

* FSx for ONTAP 파일 시스템에 설치된 ONTAP 버전을 표시합니다
* 시스템에서 iSCSI 볼륨을 관리합니다
* 볼륨에 대한 자동 확장 기능을 설정 및 해제합니다
* 스냅샷 정책을 생성하고 관리합니다
* 파일 시스템 간 복제 관계 구성 및 볼륨 복제
* 백업 관계를 구성하고 볼륨 데이터를 클라우드 스토리지에 백업합니다
* 파일 시스템 내의 볼륨 클론 생성
* ONTAP에서 직접 추가 메트릭 표시(기본 메트릭은 Amazon CloudWatch에서 수집)
* NFS 내보내기 정책 관리

