---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Workload Factory 링크는 Workload Factory 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간에 신뢰 관계와 연결을 생성합니다. 
---
= NetApp Workload Factory 링크에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 링크는 Workload Factory 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간에 신뢰 관계와 연결을 생성합니다.  이를 통해 Amazon FSx for ONTAP API를 통해서는 사용할 수 없는 특정 파일 시스템 기능을 ONTAP REST API 호출에서 직접 모니터링하고 관리할 수 있습니다.

Workload Factory를 시작하는 데는 링크가 필요하지 않지만, 어떤 경우에는 모든 Workload Factory 기능과 워크로드 기능을 잠금 해제하려면 링크를 만들어야 합니다.



== 링크가 유익한 이유

링크는 Workload Factory가 Amazon FSx for ONTAP API를 통해 기본적으로 사용할 수 없는 작업을 수행할 수 있게 해주기 때문에 유용합니다.  링크를 통해 고급 ONTAP 기능과 자동화가 가능해져 FSx for ONTAP 파일 시스템 관리가 향상됩니다.

링크를 사용하면 다음과 같은 이점이 있습니다.

* 이 링크를 통해 NetApp 콘솔은 ONTAP 명령을 FSx for ONTAP 파일 시스템으로 직접 전송할 수 있으며, 이를 통해 AWS에서 기본적으로 제공하는 것보다 더 고급 ONTAP 기능을 사용할 수 있습니다.
* 링크는 AWS Lambda를 활용하여 이벤트에 응답하여 코드를 실행합니다. 이러한 서버리스 접근 방식은 VPC에서 실행 중인 인스턴스의 종속성을 제거합니다.




== 링크 작동 방법

링크 활용 AWS Lambda. Lambda는 이벤트에 대한 응답으로 코드를 실행하고 해당 코드에 필요한 컴퓨팅 리소스를 자동으로 관리합니다. 생성하는 링크는 NetApp 계정의 일부이며 AWS 계정과 연결됩니다.

링크를 만든 후에는 하나 이상의 FSx for ONTAP 파일 시스템과 연결할 수 있습니다. 각 파일 시스템은 동일한 NetApp 계정에 있는 하나의 링크에만 연결할 수 있습니다. NetApp 계정이 여러 개인 경우 단일 파일 시스템을 다른 NetApp 계정 아래의 추가 링크에 연결할 수 있습니다.

Workload Factory에서 Storage 워크로드의 링크를 만들고 연결합니다.

Workload Factory 자격 증명 서비스에 저장된 자격 증명이나 AWS Secrets Manager에 저장된 자격 증명을 사용하여 링크를 인증할 수 있습니다.  워크로드 팩토리는 인증 모드 변경을 지원하지 않습니다.



== 비용

Lambda가 수행하는 각 거래에는 요금이 부과됩니다.  Lambda는 두 시스템 간의 프록시 역할을 하므로 Lambda가 파일 시스템의 ONTAP REST API에 요청을 보낼 때와 Workload Factory에 응답을 다시 보낼 때 요금이 발생합니다.

link:https://aws.amazon.com/lambda/pricing/["AWS Lambda 사용과 관련된 비용에 대해 자세히 알아보십시오"^]



== 링크가 필요한 경우

워크로드 팩토리에는 일부 정보를 표시하고 일부 작업을 수행하기 위한 링크가 필요합니다.  링크가 필요한 작업을 수행하려고 하지만 FSx for ONTAP 파일 시스템과 링크를 연결하지 않은 경우 Workload Factory는 해당 작업에 링크가 필요하다는 알림을 보냅니다.

링크가 필요한 기능은 다음과 같습니다.

* 사전 예방적 유지 관리, 안정성 및 비용 성능 최적화를 위한 FSx for ONTAP 파일 시스템 구성의 잘 설계된 상태
* ONTAP EMS 이벤트 모니터링 및 알림
* NetApp 자율형 랜섬웨어 보호(ARP/AI)
* FSx for ONTAP 파일 시스템 전반의 향상된 전체적인 용량 관찰 기능
* 볼륨 및 스토리지 VM 데이터 복제, 관리 및 모니터링
* SMB/CIFS 공유 및 NFS 내보내기 정책 프로비저닝 및 관리
* FSx for ONTAP 파일 시스템에서 iSCSI 볼륨 관리
* 사용자 정의 보호 SLA에 대한 스냅샷 정책 생성 및 관리
* 자동 용량 관리를 위한 Inode 관리 향상
* 탄력적 확장을 위한 볼륨 자동 증가
* 즉각적이고 즉각적인 데이터 복제를 위한 복제본 생성 및 관리
* ONTAP 버전과 같은 ONTAP 에서 직접 추가 메트릭 표시


의 방법을 link:create-link.html["FSx for ONTAP 파일 시스템에 링크 연결"]알아보십시오.
