---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Workload Factory에서 FSx for ONTAP 볼륨에 대한 스냅샷 정책을 관리합니다.  스냅샷 정책은 시스템이 볼륨에 대한 스냅샷을 생성하는 방법을 정의합니다. 
---
= 스냅샷 정책을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory에서 FSx for ONTAP 볼륨에 대한 스냅샷 정책을 관리합니다.  스냅샷 정책은 시스템이 볼륨에 대한 스냅샷을 생성하는 방법을 정의합니다.

.이 작업에 대해
FSx for ONTAP 파일 시스템에서 볼륨에 대한 스냅샷 정책을 할당, 변경 및 삭제하는 것과 같은 스냅샷 관리 작업은 스토리지 VM 수준에서 관리됩니다. 스냅샷 정책을 단일 스토리지 VM 또는 모든 스토리지 VM과 공유할 수 있습니다.

일부 관리 작업에서는 FSx for ONTAP 파일 시스템과 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Workload Factory 링크에 대해 알아보세요"] .

기본적으로 모든 볼륨은 파일 시스템의 `default` 스냅샷 정책에 연결됩니다. 대부분의 워크로드에 이 정책을 사용하는 것이 좋습니다.



== 스냅샷 정책을 변경합니다

유지할 스냅샷 정책 이름, 일정 및 복제본 수를 변경하고 변경 불가능한 스냅샷을 설정하거나 해제할 수 있습니다. 스토리지 VM 간에 정책 공유를 설정하거나 해제할 수 없습니다. 이 옵션은 스냅샷 정책을 생성하는 동안에만 사용할 수 있습니다.

.시작하기 전에
기존 스냅샷 정책을 표시하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."].. 링크가 연결되면 이 작업으로 돌아갑니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. *저장소*에서 *저장소로 이동*을 선택합니다.
. *FSx for ONTAP* 탭에서 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Storage VMS * 탭을 선택합니다.
. *저장소 VM* 탭에서 예약된 스냅샷으로 보호할 볼륨이 포함된 저장소 VM에 대한 작업 메뉴를 선택한 다음, *고급 작업*을 선택하고, *스냅샷 정책 관리*를 선택합니다.
. 스냅샷 정책 관리 페이지에서 변경할 스냅샷 정책에 대한 작업 메뉴를 선택한 다음 *편집*을 선택합니다.
. Edit snapshot policy(스냅숏 정책 편집) 대화 상자에서 필요에 따라 스냅샷 정책을 변경합니다.
. Apply * 를 선택합니다.


.결과
스냅샷 정책이 업데이트됩니다.



== 변경 불가능한 스냅샷을 활성화합니다

보존 기간 동안 삭제되지 않도록 스냅샷을 잠급니다.

.시작하기 전에
변경 불가능한 스냅샷을 활성화하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."].. 링크가 연결되면 이 작업으로 돌아갑니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. *저장소*에서 *저장소로 이동*을 선택합니다.
. *FSx for ONTAP* 탭에서 스냅샷을 잠글 볼륨이 포함된 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. *볼륨* 탭에서 보호할 볼륨에 대한 작업 메뉴를 선택합니다.
. 데이터 보호 작업 *, * 스냅샷 * 을 선택한 다음 * 스냅샷을 변경 불가 * 합니다.
. 스냅샷 변경 불가능 만들기 대화 상자에서 다음을 수행합니다.
+
.. * 스냅샷 이름 *: 잠글 스냅샷을 선택합니다.
.. 보존 기간 * 을 시간, 일, 월 또는 년 수로 설정합니다.
.. 설명을 수락합니다.


. Apply * 를 선택합니다.


.결과
이제 볼륨 스냅샷이 잠깁니다.



== 볼륨에 스냅샷 정책을 할당합니다

단일 볼륨에 스냅샷 정책을 할당하여 볼륨에 대해 예약된 스냅샷을 생성할 수 있습니다.

.시작하기 전에
스냅샷 정책을 할당하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."].. 링크가 연결되면 이 작업으로 돌아갑니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. *저장소*에서 *저장소로 이동*을 선택합니다.
. *FSx for ONTAP* 탭에서 스냅샷 정책을 할당할 볼륨이 포함된 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Storage VMS * 탭을 선택합니다.
. *저장소 VM* 탭에서 예약된 스냅샷으로 보호할 볼륨이 포함된 저장소 VM에 대한 작업 메뉴를 선택한 다음, *고급 작업*을 선택하고, *스냅샷 정책 관리*를 선택합니다.
. 스냅샷 정책 관리 페이지에서 스냅샷 정책의 작업 메뉴를 선택한 다음 *볼륨에 정책 할당*을 선택합니다.
. Assign snapshot policy(스냅숏 정책 할당) 대화 상자에서 볼륨에 할당할 스냅샷 정책을 선택하고 정책 일정을 검토합니다.
+
정책에 변경 불가능한 스냅샷이 포함되어 있고 이 스냅샷을 사용하려면 문을 수락합니다.

. 지정 * 을 선택합니다.


.결과
스냅샷 정책이 볼륨에 할당됩니다.



== 볼륨에서 스냅샷 정책을 제거합니다

볼륨의 스냅샷을 더 이상 원하지 않거나 여러 볼륨에 할당된 스냅샷 정책을 삭제하려는 경우 볼륨에서 스냅샷 정책을 제거합니다. <<스냅샷 정책을 삭제합니다,스냅샷 정책을 삭제합니다>>두 개 이상의 볼륨에 할당되어 있는 경우 모든 볼륨에서 수동으로 제거해야 합니다.

.시작하기 전에
스냅샷 정책을 제거하려면 링크를 연결해야 합니다. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법이나 새 링크를 만들고 연결하는 방법을 알아보세요."].. 링크가 연결되면 이 작업으로 돌아갑니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. *저장소*에서 *저장소로 이동*을 선택합니다.
. *FSx for ONTAP* 탭에서 스냅샷 정책을 할당할 볼륨이 포함된 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Storage VMS * 탭을 선택합니다.
. *저장소 VM* 탭에서 예약된 스냅샷으로 보호할 볼륨이 포함된 저장소 VM에 대한 작업 메뉴를 선택한 다음, *고급 작업*을 선택하고, *스냅샷 정책 관리*를 선택합니다.
. 스냅샷 정책 관리 페이지에서 스냅샷 정책의 작업 메뉴를 선택한 다음 *볼륨에 정책 할당*을 선택합니다.
. 스냅샷 정책 할당 대화 상자에서 * 없음 * 을 선택하여 스냅샷 정책을 제거합니다.
. 지정 * 을 선택합니다.


.결과
스냅샷 정책이 볼륨에서 제거됩니다.



== 스냅샷 정책을 삭제합니다

스냅샷 정책이 더 이상 필요하지 않을 경우 삭제합니다.

스냅샷 정책이 둘 이상의 볼륨에 할당된 경우 모든 볼륨에서 스냅샷 정책을 수동으로 삭제해야 <<볼륨에서 스냅샷 정책을 제거합니다,용지를 꺼내십시오>>합니다. 또는 볼륨을 이동할 수 있습니다<<볼륨에 스냅샷 정책을 할당합니다,다른 스냅샷 정책을 할당합니다>>.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. *저장소*에서 *저장소로 이동*을 선택합니다.
. 저장소 메뉴에서 *FSx for ONTAP*를 선택합니다.
. *FSx for ONTAP*에서 볼륨이 있는 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Storage VMS * 탭을 선택합니다.
. *저장소 VM* 탭에서 삭제할 스냅샷 정책이 있는 저장소 VM의 작업 메뉴를 선택한 다음, *고급 작업*을 선택하고, *스냅샷 정책 관리*를 선택합니다.
. 스냅샷 정책 관리 페이지에서 삭제할 스냅샷 정책에 대한 작업 메뉴를 선택한 다음 *삭제*를 선택합니다.
. 삭제 대화 상자에서 * 삭제 * 를 선택하여 정책을 삭제합니다.

