---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: 타겟 볼륨이 소스 볼륨이 되도록 복제 관계를 일시 중지했다가 다시 시작합니다. 
---
= NetApp Workload Factory에서 복제 관계 일시 중지 및 재개
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
복제 관계를 일시 중지하여 소스 볼륨에서 타겟 볼륨으로의 예약된 복제 업데이트를 중지합니다. 타겟 볼륨이 읽기 전용에서 읽기/쓰기로 전환됩니다. 두 볼륨 모두 최신 복제 스냅샷을 나중에 다시 동기화하기 위한 새로운 기준으로 계속 공유합니다.

.이 작업에 대해
일시 중지되면 소스 볼륨과 타겟 볼륨 간의 복제 관계가 계속 유지됩니다. 데이터 전송이 일시 중지되고 볼륨이 독립적입니다. 소스 볼륨에서 대상 볼륨으로의 변경 내용 전송을 다시 활성화하려면 복제를 다시 시작하십시오.

복제를 재개하면 대상 볼륨에 대한 모든 변경 사항이 취소되고 NetApp Workload Factory가 복제를 다시 활성화합니다.  대상 볼륨은 읽기/쓰기에서 읽기 전용으로 전환되고, 예약된 복제 간격에 따라 소스 볼륨에서 업데이트를 다시 받습니다.  복제 관계를 재개하면 대상 볼륨은 최신 초기 복제 스냅샷으로 되돌아가고, 이때 볼륨 복제 프로세스가 다시 시작됩니다.

.시작하기 전에
전송이 진행 중일 때 일시 중지하면 전송이 영향을 받지 않고 전송이 완료될 때까지 관계가 "중지 중"으로 바뀝니다. 현재 전송이 중단되면 이후 전송이므로 다시 시작되지 않습니다.



== 복제 관계를 일시 중지합니다

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 저장소 타일에서 *저장소로 이동*을 선택합니다.
. 저장소 메뉴에서 *FSx for ONTAP*를 선택합니다.
. *FSx for ONTAP*에서 업데이트할 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * 복제 관계 * 탭을 선택합니다.
. 복제 관계 탭에서 일시 중지할 복제 관계의 작업 메뉴를 선택합니다.
. Pause (Quiesce) * 를 선택합니다.
. 관계 종료 * 대화 상자에서 * 종료 * 를 선택합니다.


.결과
관계가 일시 중지되고 상태가 "일시 중지됨"으로 표시됩니다.



== 일시 중지된 복제 관계를 다시 시작합니다

복제 관계를 재개하면 복제가 중지된 동안 대상 볼륨에 대한 모든 변경 사항이 삭제됩니다.


NOTE: 마지막 데이터 복제와 소스 볼륨이 비활성화된 시간 사이에 원래 소스 볼륨에 기록된 데이터는 보존되지 않습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. 저장소 타일에서 *저장소로 이동*을 선택합니다.
. 저장소 메뉴에서 *FSx for ONTAP*를 선택합니다.
. *FSx for ONTAP*에서 업데이트할 파일 시스템의 작업 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * 복제 관계 * 탭을 선택합니다.
. 복제 관계 탭에서 재개할 복제 관계의 작업 메뉴를 선택합니다.
. Resume * 을 선택합니다.
. 관계 다시 시작 대화 상자에서 * 재시작 * 을 선택합니다.


.결과
관계가 재개되고 상태가 "복제됨"으로 표시됩니다.
