---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: 시간에 따라 발생하는 불균형을 방지하기 위해 볼륨의 용량을 확인하고 재조정합니다. 
---
= 볼륨 용량을 확인하고 재조정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FlexVol 또는 FlexGroup 볼륨 용량의 균형을 확인하고 볼륨 용량을 재조정하여 노드 내의 모든 FlexVol 볼륨이나 모든 구성 요소에 파일을 균등하게 분산하여 모든 노드가 단일 FlexGroup 볼륨의 작업 부하에 참여하도록 합니다.

.이 작업에 대해
FlexVol 볼륨과 FlexGroup 볼륨에 대해 볼륨 용량 재조정이 지원됩니다. 새로운 파일의 추가 및 파일 증가로 인해 시간이 지남에 따라 불균형이 발생할 경우 볼륨 재분산을 통해 용량을 재분배합니다. 재조정 작업을 수동으로 시작한 후 파일을 선택하고 운영 중단 없이 자동으로 이동합니다. 볼륨 전송 작업에는 파일 시스템 리소스가 사용됩니다.

각 볼륨 유형과 재조정 작업은 다음과 같이 다릅니다.

FlexVol 볼륨:: FlexVol 볼륨은 데이터 관리에 유연성을 제공하는 논리적 컨테이너로, 확장, 축소, 이동 및 효율적인 복사를 지원합니다. NAS 및 SAN 환경에서 사용할 수 있습니다.
+
--
FSx for ONTAP 파일 시스템의 한 노드 내에서 FlexVol 볼륨은 다른 FlexVol 볼륨과 비교하여 균형을 이룰 수 있습니다. 파일 시스템에 FlexVol 볼륨이 하나만 있는 경우 재조정이 불가능합니다. 파일 시스템에 노드당 두 개 이상의 FlexVol 볼륨이 있고 단일 FlexVol 볼륨을 선택한 경우, FlexVol 볼륨은 모든 FlexVol과 관련하여 균형을 이루지만, 선택한 볼륨만 이동할 수 있습니다.

--
FlexGroup 볼륨:: 반면 FlexGroup 볼륨은 고성능 및 자동 로드 분산을 위해 설계된 확장 가능한 NAS 컨테이너입니다. 트래픽을 투명하게 공유하는 여러 멤버 볼륨(구성 요소)으로 구성됩니다. FlexGroup 볼륨은 최대 60PB의 용량과 4,000억 개의 파일을 지원하여 FlexVol 한도를 초과하는 대용량을 제공합니다. 단일 네임스페이스 컨테이너를 제공하여 관리를 간소화합니다.
+
--
두 개 이상의 고가용성(HA) 쌍을 갖춘 확장형 FSx for ONTAP 파일 시스템의 여러 구성 요소에 용량이 분산됩니다. 각 구성 요소는 최대 단일 파일 크기를 지정하는 컨테이너입니다. FSx for ONTAP은 모든 노드가 단일 FlexGroup 볼륨의 워크로드에 참여하도록 균일한 방식으로 모든 구성원에게 파일을 분산합니다.

구성 요소가 모든 노드에 균등하게 분산되지 않으면 FlexGroup 볼륨 성능이 저하됩니다.

FlexGroup 볼륨 용량의 균형을 확인하려면 구성요소의 현재 레이아웃을 평가해야 합니다. 볼륨 용량을 재조정할 때 BlueXP  워크로드 공장에서는 짝수의 구성요소가 포함된 새로운 구성 레이아웃을 설계하여 모든 HA 쌍에 데이터를 균등하게 분산합니다. 이 서비스는 재조정 계획을 실행하여 읽기 및 쓰기 작업을 개선합니다.

--



NOTE: iSCSI 및 NVMe와 같은 SAN 볼륨에서는 재조정이 지원되지 않습니다.



== 볼륨의 균형을 확인하세요

FSx for ONTAP 파일 시스템에서 FlexVol 또는 FlexGroup 볼륨의 균형을 확인합니다.

.시작하기 전에
* FlexGroup 볼륨 균형은 최소 2개의 HA 쌍이 포함된 스케일아웃 구축을 사용하는 FSx for ONTAP 파일 시스템에서만 사용할 수 있습니다.
* 볼륨의 균형을 확인하려면 다음을 수행해야 합니다. link:manage-links.html["링크를 연결합니다"] . 기존 링크가 없는 경우 link:create-link.html["링크를 만듭니다"] 파일 시스템의 링크를 연결하려면 * 계정 이름 * 아래에서 * 링크 * 를 선택합니다. 링크가 연결되면 이 작업으로 돌아갑니다.


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage * 에서 * Go to storage inventory * 를 선택합니다.
. *FSx for ONTAP* 탭에서 재조정할 볼륨이 포함된 파일 시스템의 3개 점 메뉴를 선택한 다음 *관리*를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. 볼륨 탭에서 표 상단에 있는 *볼륨 잔액 확인*을 선택하세요.
. 볼륨 잔액 창에서 다음의 잔액 상태를 검토하세요.
+
** FlexGroup 볼륨
** FlexVol 볼륨
+
볼륨이 불균형한 경우 다음을 고려하세요. <<볼륨 용량 재조정,재조정>> .







== 볼륨 용량 재조정

하나 이상의 불균형 볼륨을 재조정합니다.


NOTE: 작업 부하 팩토리 관리자는 다음을 수행할 수 있습니다. <<볼륨 재조정 작업 중지,리밸런싱을 중지하다>> 수술 중.

.시작하기 전에
* <<볼륨의 균형을 확인하세요,볼륨의 균형을 확인하세요>> 볼륨을 재조정하기 전에,
* 볼륨을 재조정하려면 다음을 수행해야 link:manage-links.html["링크를 연결합니다"]합니다. 기존 링크가 없는 경우 link:create-link.html["링크를 만듭니다"] 파일 시스템의 링크를 연결하려면 * 계정 이름 * 아래에서 * 링크 * 를 선택합니다. 링크가 연결되면 이 작업으로 돌아갑니다.
* 재조정한 볼륨의 기존 스냅샷은 부분적으로 변경되며 볼륨 데이터를 복원하는 데 사용할 수 없지만 재조정 후 생성된 새 스냅샷은 볼륨 데이터를 복원하는 데 사용할 수 있습니다.
* FlexVol 볼륨은 모든 볼륨 리소스의 균형을 균등하게 맞추기 위해 전체적으로 재조정하는 것이 가장 좋습니다. 선택 해제된 볼륨은 균형 조정 절차에 적극적으로 참여하지 않습니다.


[role="tabbed-block"]
====
.FlexVol 볼륨
--
FSx for ONTAP 파일 시스템의 한 노드 내에서 FlexVol 볼륨은 다른 FlexVol 볼륨과 비교하여 균형을 이룰 수 있습니다. 파일 시스템에 노드당 두 개 이상의 FlexVol 볼륨이 있고 단일 FlexVol 볼륨이 선택된 경우, FlexVol 볼륨은 모든 FlexVol과 관련하여 균형을 이루지만, 선택된 볼륨만 이동할 수 있습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage * 에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 재조정할 볼륨이 포함된 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. 볼륨 탭에서 표 상단에 있는 *볼륨 잔액 확인*을 선택하세요.
. 볼륨 잔액 창에서 선택적으로 FlexVol 잔액 요약에서 *데이터 분포*를 선택하여 집계별 사용된 용량을 확인합니다.
. *재균형*을 선택하면 하나 이상의 불균형 볼륨을 재균형하게 조정할 수 있습니다.
. 재조정 마법사에서 다음 단계를 따르세요.
+
.. *최대 전송 속도*: 선택 사항. 기본적으로 비활성화되어 있습니다. 파일 시스템에서 볼륨 이동 대역폭을 제한하고 나가는 볼륨 복제 트래픽의 속도를 늦추려면 스로틀을 활성화하십시오.
+
스로틀 값을 MB/s 단위로 입력합니다

+
다음 * 을 선택합니다.

.. 모든 FlexVol 볼륨의 현재 레이아웃과 제안된 레이아웃을 검토한 후 *다음*을 선택합니다.
.. 재조정 작업을 시작하기 전에 무슨 일이 일어날지와 참고 사항을 주의 깊게 검토하세요.


. Rebalance * 를 선택합니다.


.결과
FlexVol 볼륨이 재조정되었습니다. 작업이 완료되면 파일 시스템이 원래 값으로 다시 스로틀됩니다.

--
.FlexGroup 볼륨
--
데이터는 구성원 볼륨 전체에 재분배되어 FlexGroup 볼륨의 균형을 재조정합니다. 선택한 레이아웃에 따라 재조정 작업에서 FlexGroup 멤버 볼륨이 추가되고 프로비저닝된 볼륨의 크기가 늘어날 수 있습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage * 에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 재조정할 볼륨이 포함된 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. Volumes(볼륨) 탭에서 표 상단에 있는 * Check FlexGroup balance * 를 선택합니다.
. FlexGroup balance 창에서 * Rebalance * 를 선택하여 하나 이상의 불균형 볼륨을 재조정합니다.
. 재조정 마법사에서 원하는 데이터 배포 레이아웃을 선택합니다.
+
** * 성능 최적화 * (권장): FlexGroup 구성원 볼륨의 수와 볼륨의 프로비저닝된 크기를 늘립니다. NetApp 모범 사례를 따릅니다.
** * Restricted *: 복제 관계에서 볼륨을 지원합니다. FlexGroup 구성원 볼륨 수와 프로비저닝된 볼륨 크기는 동일하게 유지됩니다. 선택한 모든 볼륨이 복제 관계에 참여하는 경우 기본적으로 선택됩니다.
** * 수동 *: HA 쌍당 원하는 FlexGroup 구성원 볼륨 수를 선택합니다. 선택 항목에 따라 FlexGroup 구성원 볼륨의 수와 볼륨의 프로비저닝된 크기가 증가할 수 있습니다.


. * Throtling *: 선택 요소입니다. 기본적으로 비활성화되어 있습니다. 파일 시스템에서 볼륨 이동 대역폭을 제한하고 나가는 볼륨 복제 트래픽의 속도를 늦추려면 스로틀을 활성화하십시오.
+
스로틀 값을 MB/s 단위로 입력합니다

. 레이아웃 비교 보기를 선택한 후 * 다음 * 을 선택합니다.
+
** 볼륨 레이아웃 비교
** FSx for ONTAP 레이아웃 비교


. 필요에 따라 재조정 전에 볼륨 이동 목록을 다운로드합니다.
. Rebalance * 를 선택합니다.


.결과
FlexGroup 멤버 볼륨은 재조정 중에 한 번에 하나씩 이동됩니다. 작업이 완료되면 파일 시스템이 원래 값으로 다시 스로틀됩니다.

--
====


== 볼륨 재조정 작업 중지

리밸런싱 작업은 언제든지 중지할 수 있습니다. 중단되지 않습니다. 작업을 중지하면 활성 볼륨 이동이 중단됩니다.

나중에 다른 재조정 작업을 시작할 수 있습니다.

.단계
. 리밸런싱 작업을 시작한 후 볼륨 잔액 페이지에서 *리밸런싱 중지*를 선택하세요.
. 재조정 중지 대화 상자에서 *중지*를 선택합니다.


.결과
볼륨 재조정 작업이 중지되고 활성 볼륨 이동이 중단됩니다.
