---
sidebar: sidebar 
permalink: restore-volume-from-snapshot.html 
keywords: restore volume, snapshot 
summary: 볼륨에 삭제되거나 손상된 파일이 있을 때 스냅샷에서 FSx for ONTAP 볼륨을 복원합니다. 
---
= 워크로드 팩토리의 스냅샷에서 볼륨 복원
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
워크로드 팩토리에서는 스냅샷의 데이터를 기존 볼륨이나 새 볼륨으로 복원할 수 있습니다.  복원 작업을 통해 볼륨에 삭제되거나 손상된 파일이 있는 경우 특정 시점으로 복구할 수 있습니다.

.이 작업에 대해
스냅샷의 데이터를 기존 볼륨이나 새 볼륨으로 복원할 수 있습니다.

스냅샷에서 새 볼륨을 생성하면 볼륨 크기에 관계없이 몇 초 내에 전체 볼륨의 복사본이 생성됩니다.  새로 생성된 복사본은 새로운 볼륨을 나타냅니다.

.시작하기 전에
스냅샷에서 볼륨을 생성하기 전에 다음과 같은 제한 사항을 고려하십시오.

* 볼륨의 기존 스냅샷 복사본이 있는 경우에만 스냅샷에서 볼륨을 복원할 수 있습니다.
* 권한 모델 변경: 이 작업을 사용하여 NAS(Network-Attached Storage) 프로토콜 유형을 전환하는 경우 보안 스타일이 제공하는 권한 모델도 전환할 수 있습니다. 파일 액세스 권한 문제가 발생할 수 있습니다. 이 문제는 권한 설정에 NAS 클라이언트 도구를 사용하여 관리자 액세스 권한으로만 수동으로 해결할 수 있습니다.


.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage * 에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 볼륨이 있는 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * Volumes * 탭을 선택합니다.
. Volumes * 탭에서 스냅샷에서 복원할 볼륨에 대한 3점 메뉴를 선택합니다.
. *데이터 보호 작업*을 선택한 다음 *스냅샷 관리*를 선택합니다.
. 스냅샷 관리 페이지에서 복원할 스냅샷의 세 점 메뉴를 선택한 다음, *복원*을 선택합니다.
. 스냅샷에서 볼륨 복원 대화 상자에서 다음 옵션 중에서 선택하세요.
+
** *새 볼륨으로 복원*을 선택합니다.
+
복원된 볼륨 이름 * 필드에 복원할 볼륨의 고유한 이름을 입력합니다.

** 스냅샷의 데이터를 기존 볼륨으로 복원합니다.  이 작업은 스냅샷 생성 시간 이후에 수정된 모든 데이터를 영구적으로 삭제합니다.
+
계속하려면 설명을 수락하십시오.



. Restore * 를 선택합니다.

