---
sidebar: sidebar 
permalink: reverse-replication.html 
keywords: reverse replication, change replication 
summary: 타겟 볼륨이 소스 볼륨이 되도록 복제 관계를 반대로 전환합니다. 
---
= BlueXP  워크로드 팩토리의 복제 관계를 되돌립니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  워크로드 팩토리에서의 복제 관계를 반대로 변경하여 타겟 볼륨이 소스 볼륨이 되도록 합니다.

역방향 작업은 다음과 같이 지원됩니다.

* 두 개의 FSx for ONTAP 파일 시스템
* FSx for ONTAP 파일 시스템 하나와 온프레미스 ONTAP 클러스터 하나를 사용할 수 있습니다


복제를 중지하고 타겟 볼륨을 변경한 후에는 해당 변경 내용을 다시 소스 볼륨에 복제할 수 있습니다. 이 프로세스는 타겟 볼륨에서 잠시 동안 작업하고 볼륨의 역할을 전환하려는 재해 복구 시나리오에서 일반적입니다.

.이 작업에 대해
복제를 되돌리고 다시 시작하면 볼륨의 소스 및 타겟 역할이 전환되고 타겟 볼륨은 새 소스 볼륨이 되고 소스 볼륨은 새 타겟 볼륨이 됩니다. 또한 역방향 작업은 새 타겟 볼륨의 내용을 새 소스 볼륨의 내용으로 덮어씁니다. 복제를 두 번 반대로 수행하면 원래 복제 방향이 다시 설정됩니다.


NOTE: 마지막 데이터 복제와 소스 볼륨이 비활성화된 시간 사이에 원래 소스 볼륨에 기록된 데이터는 보존되지 않습니다.

.시작하기 전에
새 타겟 볼륨의 변경 내용이 새 소스 볼륨으로 덮어쓰기되므로 소스 및 타겟 볼륨의 현재 및 향후 역할을 알고 있어야 합니다. 잘못 사용하면 의도하지 않은 데이터가 손실될 수 있습니다.

.단계
. 중 하나를 사용하여 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. Storage에서 * Go to storage inventory * 를 선택합니다.
. FSx for ONTAP * 탭에서 업데이트할 파일 시스템의 세 점 메뉴를 선택한 다음 * 관리 * 를 선택합니다.
. 파일 시스템 개요에서 * 복제 관계 * 탭을 선택합니다.
. 복제 관계 탭에서 반전할 복제 관계의 세 점 메뉴를 선택합니다.
. 관계 반대 * 를 선택합니다.
. 관계 반대 대화 상자에서 * 반대 * 를 선택합니다.

